### ISSUE TITLE
WETH does not show up for all wallets types after trading ETH to WETH 

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#650] opened 2022-01-06 21:52 UTC
**Brief Description:**
Weth no longer shows up with a balance for all wallet types after trading ETH to WETH. Doing a trade from ERC-20 to WETH fixes the issue. I believe this is caused because the "trade" from ETH to WETH is a contract deposit and not a trade. https://etherscan.io/tx/0x947a29772a9c7f123fffb650bede6dcc07a1af716de221c93b8a18d93564346f for example

**Recreation Steps:**
1. Trade into WETH with ETH on app.shapeshift.com
2. Once the trade completes notice how the weth doesn't show up with a balance

**Acceptance Criteria:**
- Find the reporting issue for KK, MM and native
- Fix the issue and have ops test the environment

**Comment by 0xean** [comment] 2022-01-07 16:10
![Screen Shot 2022-01-07 at 9 10 04 AM](https://user-images.githubusercontent.com/15096737/148572106-3fbefc12-d2af-43b6-b8cd-8b92193499f4.png)

Can you please add some more details to this ticket, or a screenshot? I am paired with metamask and see my dust balance of wETH on the dashboard.

**Comment by tshifty** [comment] 2022-01-07 16:56
![Address_0xE7F92E3d5FDe63C90A917e25854826873497ef3D___Etherscan](https://user-images.githubusercontent.com/94189400/148578664-b8babd73-3112-4352-8966-9474f6f465b8.jpg)

**Comment by tshifty** [comment] 2022-01-07 17:01
![kkweth](https://user-images.githubusercontent.com/94189400/148579323-ef3d754b-942d-41f5-96c9-f66e9d1787d6.jpg)
![Address_0xf6Fb864F185f14E8d7da00c0E4a55a09E4152Ff6___Etherscan](https://user-images.githubusercontent.com/94189400/148579351-28676e82-0151-4741-8458-dd6890bf827a.jpg)

**Comment by 0xean** [comment] 2022-01-07 17:19
thanks @tshifty - super helpful, can you shoot me the address of one of these wallets? curious if its the same "WETH" since there are multiple versions WETH

**Comment by tshifty** [comment] 2022-01-07 17:25
Keepkey: https://etherscan.io/address/0xf6Fb864F185f14E8d7da00c0E4a55a09E4152Ff6
Native wallet: https://etherscan.io/address/0xE7F92E3d5FDe63C90A917e25854826873497ef3D
Metamask: https://etherscan.io/address/0x71d20703f2a66522f3d9d18673693a968277aeee

**Comment by 0xean** [comment] 2022-01-07 17:29
Okay, thanks! It's all the same WETH, that rules that out

**Comment by tshifty** [comment] 2022-01-07 17:32
Did you trade into Weth using that account? or did you send weth to it from another address?

**Comment by tshifty** [comment] 2022-01-07 22:02
Can this be moved over to the bug board?

**Comment by 0xdef1cafe** [comment] 2022-01-12 01:44
@tshifty did this happen immediately after trading, before refreshing the page? does it show up correctly after refreshing the page? 

if it does work after a refresh, https://github.com/shapeshift/web/issues/706#issuecomment-1010314312 is related and will address it. we're not refetching the account with the new asset in it once a new tx comes in, if you previously didn't have the asset in your portfolio

**Comment by tshifty** [comment] 2022-01-12 02:25
Refresh doesn't fix the issue. the only work around I have found is to trade an ERC-20 to WETH.

**Comment by 0xean** [comment] 2022-01-18 14:15
To add a summary of what we know for the next person who looks at this:

We aren't handling wrapping of ETH into WETH as a transaction that is understood by the system.

**Comment by helr441** [comment] 2022-01-20 04:58
Hmm, looking at the network calls, it seems dev-api.ethereum.shapeshift.com is not returning WETH in the list of tokens after the ETH->WETH transaction. Should we rope in the shapeshift/unchained folks?

![Screenshot 2022-01-20 125736](https://user-images.githubusercontent.com/96822203/150276286-442fee0f-c10c-4dd6-9f5d-e349b28a7ca5.jpg)

**Comment by 0xean** [comment] 2022-01-27 12:53
@helr441 plans to take a look at this further over the coming 4-5 days.

**Comment by helr441** [comment] 2022-02-04 01:41
Hi, an update - I haven't been able to spend much time on this so far. It is on my list of to-dos, nevertheless.

**Comment by 0xdef1cafe** [comment] 2022-02-11 21:43
closing as root cause is captured in https://github.com/shapeshift/web/issues/706 and this is not actually specific to WETH

**Comment by 0xdef1cafe** [comment] 2023-02-05 23:44
@kaladinlight @tshifty is this fixed/can be closed?

**Comment by kaladinlight** [comment] 2023-02-06 17:35
> @kaladinlight @tshifty is this fixed/can be closed?

Not fixed, though still low priority edge case imo. I will take a look at blockbook in more detail surrounding contract events and see if this will be fixed in blockbook v4 upgrade (I would think it should be), and we can go from there

**Comment by 0xdef1cafe** [comment] 2023-05-02 22:33
closing as stale and users aren't reporting

**Closed by 0xdef1cafe** 2023-05-02 22:33 UTC
Labels: low priority
