### ISSUE TITLE
Unable to trade out of XRP20 on ETH

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5598] opened 2023-11-09 00:29 UTC
### Overview

Every time trying to trade out of XRP20 on Eth, it gives the error "Something went wrong"

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to trade page and enter XRP20 on Eth as input asset
3) Confrim trade
4) Note that it gives the error "Something went wrong"
![image](https://github.com/shapeshift/web/assets/100157997/69076b9c-2b04-42f3-877d-3df906410c26)
![image](https://github.com/shapeshift/web/assets/100157997/b1b36714-8dfa-40c5-8163-c1e28758375e)
![image](https://github.com/shapeshift/web/assets/100157997/4074bbe7-6026-46d8-8a1c-201d35df7768)

### Acceptance Criteria

Should be able to trade out of XPR20 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment] 2023-11-21 22:45
error from preview trade:
 "errorType": "UnsupportedToken",
    "description": "Token 0xe4ab0be415e277d82c38625b72bd7dea232c2e7d is unsupported: Transfer token out of settlement contract to arbitrary recipient 0xcd7328a5d376d5530f054eaf0b9d235a4fd36059 failed: transaction failed: Reverted"
}
error when trying to broadcast it:
![image](https://github.com/shapeshift/web/assets/100157997/4fb3231a-192c-43dd-873e-621135b91488)

**Comment by gomesalexandre** [comment] 2023-11-22 18:06
@MBMaria Closing this as this is an upstream issue with 0x - reproducible with Matcha as well. Basically, broadcasting this Tx would revert which is why we're able to get a quote at quote time, but aren't able to get a quote at pre-broadcast time when enforcing validation.

<img width="1508" alt="image" src="https://github.com/shapeshift/web/assets/17035424/0645b06a-3051-4f10-8580-b05857159443">

The ideal fix for this would be not to have that quote at all, unfortunately we can't do that as this would imply *enforcing* validation at the first quote time (validation means checking for allowance, account balance and simulating the actual swap Tx).

We can't do that, since enforcing validation would mean you could only get quotes for pairs you have balance for and have already approved.

Unfortunate edge case here for this specific, but trying with another swapper may be the goer?

**Closed by gomesalexandre** 2023-11-22 18:06 UTC
Labels: needs engineering
