### ISSUE TITLE
Wallet load time increasing

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7814] opened 2024-09-25 21:49 UTC
### Overview

When loading your wallet from a cleared cache state, the load time is getting pretty long again. No wallet balance at all until 1min, tx's come in at 1min 30 and no graph til about 3min 3.

### References and additional details

https://jam.dev/c/19c38704-b172-41bc-b1f1-0b57078766bf

### Acceptance Criteria

Load time should be a little quicker ideally.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment] 2024-09-26 09:57
@MBMaria FYI this is how things look in prod with my hyuge history testing wallet and on tethered data:

https://jam.dev/c/0143ba02-3886-438e-8386-ff5e214539e7

Note that the seemingly borked BTC Tx history is getting fixed next release

**Comment by gomesalexandre** [comment] 2024-09-26 10:31
Closing as dupe of https://jam.dev/c/3ba85083-6d00-4411-9081-8b08abb236ac

**Comment by gomesalexandre** [comment] 2024-09-27 17:53
Reopening so issue has a closer PR

**Closed** 2024-10-02 07:23 UTC
Labels: bug, needs engineering
