### ISSUE TITLE
Trade pairs reset to ETH->FOX default when clearing top input box

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2395] opened 2022-08-10 22:06 UTC
### Overview

If you have a trade pair other than ETH -> FOX in the trade widget, when you clear/backspace the top input box, the trade pair will reset back to the ETH->FOX default.

### References and additional details

1) Log into app.shapeshift and connect to any wallet
2) Enter a different asset pair in the trade widget
3) Backspace the top input box to zero and notice the trade pairs will reset to ETH -> FOX automatically

https://user-images.githubusercontent.com/100157997/184028641-f8542113-c939-4a26-8651-e2b5126e66a5.mp4

### Acceptance Criteria

Trade Pairs should remain as selected until changed by user or refresh/back to dashboard etc. 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment] 2022-08-10 23:23
@MBMaria I believe this has been fixed in some recent swapper bug fix work.

Can you please try the latest Fleek build off develop and confirm?

https://bafybeif7crizpqvhwaezgj65xqknmgxfimobdzh3qvkbhoj276i75scii4.on.fleek.co/

**Comment by MBMaria** [comment] 2022-08-10 23:29
@0xApotheosis yep that fixes it. After playing around with it, noticing that if you backspace both fields that it will also reset to ETH-FOX.

**Comment by 0xApotheosis** [comment] 2022-08-10 23:53
Ah yeah I see.

It's caused by this logic change: https://github.com/shapeshift/web/commit/92d3eb376bf6794448de73dfadabc72900446671#diff-62ce1d676340482a29d6dcef3d58bd421246f2b07ee978dc64ac7aca931af407L85 in https://github.com/shapeshift/web/pull/2285.

I think I know a quick fix, one sec.

**Closed** 2022-08-11 10:19 UTC
