### ISSUE TITLE
FOX claims not working consistently

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2103] opened 2022-06-30 22:00 UTC
### Overview

When claiming fox it will complete the transaction in some wallets but not all. Was able to claim on native and metamask but not keepkey while other ops assistants could claim on KK.

### References and additional details

1) Open app.shapeshift.com and connect to KeepKey
2) Select Defi page and click on the FOX Token Staking card.
3) In the overview tab select the "Confirm Claim" button.
4) Notice a toast pop up stating "Transaction Failed"

Browser: Chrome incognito. Closed tab and reopened, no other tabs open with app.shapeshift running. Still could not claim. Closed window completely and reopened but could not get past the "Transaction Failed" error. 
This was in KeepKey wallet, however I could claim FOX in Metamask and native. Others could claim in KK and native, while others could not claim in KK or Native.
![image](https://user-images.githubusercontent.com/100157997/176785905-864d729c-57f2-48cd-8567-3e8da67789ab.png)
![image](https://user-images.githubusercontent.com/100157997/176785949-ea1f1a6f-252d-4687-bdbc-6f3d9657d963.png)

### Acceptance Criteria

When FOX is listed as available to claim, the tx should complete consistently across wallets. 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment] 2022-06-30 22:02
https://discord.com/channels/554694662431178782/873244924026449940/992186183952113684

**Comment by gomesalexandre** [comment] 2022-07-01 12:02
The console error is correct, this is happening because of the warmup/cooldown vesting period in the contract, see https://discord.com/channels/554694662431178782/986388017159733288/986395431682588712

https://github.com/shapeshift/foxy/blob/ff815e5ac85cda363b3979cac78646770759a146/src/contracts/Staking.sol#L231-L238
https://github.com/shapeshift/foxy/blob/4f15cb6a05c0e446c0068aa6c4a361698c1f488f/test/stakingTest.ts#L332-L345

Looks like we could use the `warmupInfo` / `cooldownInfo` method to fetch whether or not it is possible to claim currently, and disable the claim button in case one of these two is currently active. I'll sync with @toshiSat on this one

**Comment by gomesalexandre** [comment] 2022-07-01 15:47
I just confirmed with we can use the [`canClaimWithdraw`](https://github.com/shapeshift/lib/blob/f44bc8fe4a50951207632fdad4106b645d91686d/packages/investor-foxy/src/api/api.ts#L541) investor-foxy method to check if we can claim beforehand. This method effectively mimicks [`_isClaimWithdrawAvailable`](https://github.com/shapeshift/foxy/blob/ff815e5ac85cda363b3979cac78646770759a146/src/contracts/Staking.sol#L274) from the FOXy `Staking.sol` contract.

That will be a relatively small PR, consuming this method in web.

The question for @shapeshift/product is, do we simply want to disable the button if the claim withdraw is unavailable, or is there any additional UX we'd expect for this?

**Comment by reallybeard** [comment] 2022-07-01 16:38
> I just confirmed with we can use the [`canClaimWithdraw`](https://github.com/shapeshift/lib/blob/f44bc8fe4a50951207632fdad4106b645d91686d/packages/investor-foxy/src/api/api.ts#L541) investor-foxy method to check if we can claim beforehand. This method effectively mimicks [`_isClaimWithdrawAvailable`](https://github.com/shapeshift/foxy/blob/ff815e5ac85cda363b3979cac78646770759a146/src/contracts/Staking.sol#L274) from the FOXy `Staking.sol` contract.
> 
> That will be a relatively small PR, consuming this method in web.
> 
> The question for @shapeshift/product is, do we simply want to disable the button if the claim withdraw is unavailable, or is there any additional UX we'd expect for this?

Yah expected UX would be to disable the button if they cannot claim.

**Comment by gomesalexandre** [comment] 2022-07-03 19:35
Agreed for @NeOMakinG to take this one

**Comment by gomesalexandre** [comment] 2022-07-25 20:35
Wrongly automagically closed by #2225

**Comment by gomesalexandre** [comment] 2022-07-29 12:49
Closing in favor of https://github.com/shapeshift/lib/issues/921

**Closed by gomesalexandre** 2022-07-29 12:49 UTC
Labels: keepkey
