### ISSUE TITLE
signed 0x permit2 should be durable across updated quotes

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#8269] opened 2024-12-04 21:26 UTC
Please validate that this works as expected before implementation (permit2 isn't coupled to a quote)

- a signed permit isn't unique to a specific quote and should be fine to be used if the quote is updated 
- ***validate*** this and implement a solution here so that we are able to better update quotes without having to have a user sign an updated permit. 
- we may need to decouple the permit2 signing from the transaction itself 
- we need track the expiration on the permit2 to make sure it doesn't time out before the quote is executed.

**Comment by 0xean** [comment] 2024-12-04 21:37
as a follow up to this ticket we should either then add updates to the quote or if we cannot accomplish this then update the network fees at the least.

**Comment by gomesalexandre** [comment] 2024-12-10 07:22
> as a follow up to this ticket we should either then add updates to the quote or if we cannot accomplish this then update the network fees at the least.

@0xean FYI this issue is actually decoupled from 0x permit2 work

 https://github.com/shapeshift/web/pull/8313 went in yesterday which closes https://github.com/shapeshift/web/issues/8271 - in its current state, https://github.com/shapeshift/web/issues/8271 was effectively a subset of this issue, so to make it Li.FI-y and not mix issues, 8313 closed it by effectively fixing Li.Fi network fees when we can (tokens with approval/native assets).

It did *not* do any kind of network fees refetch since that's the scope of this issue.
Will start work on this one which will achieve what we originally intended for Li.Fi (but even better, given we now have correct network estimates from the get-go at rate time in 2 out of 3 cases 🎉)

**Comment by NeOMakinG** [comment] 2024-12-18 09:01
https://github.com/0xProject/0x-settler/blob/ac08d41d594288dd6c240d743706514a67ccc884/README.md?plain=1#L776

Initially I saw something that made me guess that the permit2 message was containing some data linked to the quote:
```
PermitWitnessTransferFrom(TokenPermissions permitted,address spender,uint256 nonce,uint256 deadline,SlippageAndActions slippageAndActions)
SlippageAndActions(address recipient,address buyToken,uint256 minAmountOut,bytes[] actions)
TokenPermissions(address token,uint256 amount)
```

`PermitWitnessTransferFrom` contains actions, `nonce` could also be sent through the calldata for compare reasons

So I decided to ask the ZRX team a confirmation, they confirmed it's impossible to use another permit message with a second quote because the calldata contain some informations that the permit2 message also contain:


https://discord.com/channels/435912040142602260/1159284824750702682/1318694036457918505

<img width="937" alt="Image" src="https://github.com/user-attachments/assets/f06d740a-1963-49a3-bb4d-938a2d3077f5" />

I think we're stuck because of upstream on this issue, closing it, if you feel like there is another solution, feel free to open again 🙏

**Closed by NeOMakinG** 2024-12-18 09:01 UTC
