### ISSUE TITLE
After a successful approval with Portals it wont allow the trade to complete

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#8301] opened 2024-12-06 03:11 UTC
### Overview

If you do a Portals trade that needs an approval, the approval will go through then ask to sign the transaction, which you can select but then nothing happens. If you do another transaction then come back to the same one you did the approval for previously, you can then complete the trade with no approval with no issues

### References and additional details

![image](https://github.com/user-attachments/assets/d111d004-acc2-4bc1-b85f-5b6c6674a5b6)
release:  https://jam.dev/c/afa3c4d8-b4de-4723-b064-4ed214a09445 
prod: https://jam.dev/c/ae334ee0-5e88-4ece-b7b5-1ee7d0686c6e

### Acceptance Criteria

Should be able to sign Portals trade after approving transaction

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment] 2024-12-06 03:33
Same root cause as https://github.com/shapeshift/web/issues/8286 after double-checking release Jam, closing as dupe after discussing with @MBMaria

**Closed by gomesalexandre** 2024-12-06 03:33 UTC
Labels: bug, needs engineering
