### ISSUE TITLE
rFOX amount staked

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#7346] opened 2024-07-09 21:51 UTC
Currently we display the fiat value for FOX deposited, but ideally we can see the FOX amount as well. Tooltip might be easiest, but if we could click the numbers to toggle between amounts that could also be fun. 

![Image](https://github.com/shapeshift/web/assets/8991325/685ded84-6ad8-4eee-8765-736243f0f91c)

Might want to adjust copy too so it's not redundant.

**Comment by 0xean** [comment] 2024-07-15 22:44
closing as dupe of #7318

**Closed by 0xean** 2024-07-15 22:44 UTC
Labels: needs grooming
