### ISSUE TITLE
MM snaps says installed but only EVMs are showing in wallet

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7376] opened 2024-07-15 22:21 UTC
### Overview

When connecting to MM, it says that snaps is installed but the wallet only shows EVMs. 
To access UTXOs you again you need to uninstall mm and reinstall the extension and then re-add snaps. 

### References and additional details

Open an incognito browser, making sure MM wallet is locked, then enter password and connect to see only evms and errors in console. 
![image](https://github.com/user-attachments/assets/72008411-bf81-440f-81ea-9af2ae91de22)
![image](https://github.com/user-attachments/assets/7bbb1475-edc3-49e4-95be-e8d33be275cb)
https://jam.dev/c/5c5505c6-e220-41bf-bd9e-5fe6c41adc0e

### Acceptance Criteria

UTXOs should appear in wallet when MM snaps is installed

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment] 2024-08-09 16:08
@MBMaria I'm unable to repro after a full cache clear - can you still repro after fully quitting your Chrome app and restarting?

https://jam.dev/c/bd12b75f-8a8c-4f84-b7c5-618c1a048119

Locked state shouldn't really be an issue here - the moment MM is unlocked is when we actually connect in the app, deriving both EVM and non-EVM accounts

**Comment by 0xean** [comment] 2024-08-19 22:13
@purelycrickets - any chance you are able to repro with @MBMaria out this week? 

Hoping to repro or close

**Comment by purelycrickets** [comment] 2024-08-20 18:08
I was unable to reproduce the this issue with many attempts to shuffle up the connectivity flow with regards to wallet being locked and priority of connecting first vs unlocking first with both a hardware wallet and software wallet connected through MM. 

I was able to get UTXO account balances each time: 
![Screenshot 2024-08-20 at 12 07 51 PM](https://github.com/user-attachments/assets/eecad0fc-959b-42b5-be90-247522abfec5)

Errors in logs look to be related to our proxy endpoint and have nothing to do with MM or snaps.

**Comment by 0xean** [comment] 2024-08-20 18:16
Thanks @purelycrickets - we are gonna close this for now then. Appreciate the assistance.

**Comment by MBMaria** [comment] 2024-09-25 06:54
gm - still finding this happens (doesn't seem to happen every time but it happens fairly often). Usually if i uninstall mm extension and reinstall it then snaps will work and utxos will show in wallet. This time (and i repeated it twice) i uninstalled mm extension, reinstalled and added snaps - however utxos are not showing
https://jam.dev/c/52307ca8-c642-4d9d-9cc9-a22c1c8e99dd

**Closed** 2024-09-25 22:48 UTC
Labels: bug, needs operations
