### ISSUE TITLE
Cowswap trade on Gnosis via Rabby does not work

### ISSUE THREAD

**Issue by koeppelmann** [shapeshift/web#5138] opened 2023-08-22 07:49 UTC
### Overview

Connected with Rabby/ Chrome/ iOS.
Switched to Gnosis in the Shapeshift UI -> Rabby also switches to Gnosis.
Want to do trade via Cowswap.
When initiating the trade as expected message to sign pops up.

Issue 1) It is not formatted
Issue 2) It seems that it is signing a message for mainnet and not for Gnosis

2) is likely the reason why after signing I get an error message.
<img width="597" alt="Screenshot 2023-08-22 at 09 38 25" src="https://github.com/shapeshift/web/assets/2594089/eb2a1c82-edf4-48ab-8eaa-09c1cb345d84">

--
<img width="397" alt="Screenshot 2023-08-22 at 09 38 39" src="https://github.com/shapeshift/web/assets/2594089/f68f30cf-4b8f-4341-9acd-eaa1982159f5">
--
<img width="354" alt="Screenshot 2023-08-22 at 09 38 46" src="https://github.com/shapeshift/web/assets/2594089/87835c92-dda7-4e9a-9162-a6727a63e354">

### References and additional details

..

### Acceptance Criteria

..

**Comment by twblack88** [comment] 2023-08-25 14:57
@koeppelmann thanks so much for bringing this in! We've got some rough edges to smooth on COWswap and we absolutely welcome your feedback. If you're trying to use it as walletconnect we are going to prioritize that at the next roadmap call (hopefully) this might be a great use case. 

@gomesalexandre I think Rabby runs their own RPC IIRC, they're stack is 🐐 -ed but that flow makes sense.

**Comment by gomesalexandre** [comment] 2023-08-28 09:09
@twblack88 this wouldn't be related to the JSON-RPC endpoint used, but to:

1. [`wallet_switchEthereumChain` ] method not being triggered. Disregard my previous message about Rabby supposedly not supporting this method, this is irrelevant of the wallet used. The reason why switch chain isn't triggered is because this is a signature, not a transaction. Hence, we don't *need* to switch chains, see this CoW signature while connected to BSC:

<img width="1527" alt="Screenshot 2023-08-28 at 10 48 59" src="https://github.com/shapeshift/web/assets/17035424/16596c79-e071-445e-9016-9be52f1b19b4">

And the matching CoW Tx on Gnosis chain: https://explorer.cow.fi/gc/orders/0xf46f02d45e3c2d3d528105f1448361662a8f9ba61e0a6f61dd456fe834a5e4f45daf465a9ccf64deb146eeae9e7bd40d6761c98664ec666b?tab=overview

@twblack88 I think this raises a valid point for signatures, while the wallet doesn't need to be connected to a specific chain, it can definitely confusing for users. What about we switch chains before signing messages, similar to before signing and broadcasting a Tx?

2. Confirmed with MM our messages are not currently structured, at least not from a user-facing perspective. This is CoW's UI for comparison:

<img width="864" alt="image" src="https://github.com/shapeshift/web/assets/17035424/ef2b0d4f-6d2c-46e4-8c96-e58aee259f14">

Looking at hdwallet, we indeed use `personal_sign` vs. `eth_signTypedData_v4` if applicable for EIP-712. We should implement hdwallet signing using `eth_signTypedData_v4` to make this human-readable.

**Comment by twblack88** [comment] 2023-09-27 16:47
> We should implement hdwallet signing using eth_signTypedData_v4 to make this human-readable.

Yeah agreed, slot in when we have the time to reduce UX confusion.

**Comment by gomesalexandre** [comment] 2023-12-19 12:24
@twblack88 I wasn't able to repro this - Rabby signing is happy and I was able to complete a CoW swap end-to-end

<img width="1563" alt="image" src="https://github.com/shapeshift/web/assets/17035424/404cb993-e555-45f5-a6f9-e62e7aefbcad">

I suggest we close this and open an issue for `eth_signTypedData_v4` instead. This is a relatively high effort with huge risks for regressions (in particular signing with Ledger and Trezor through MM, see https://docs.metamask.io/wallet/how-to/sign-data/). I do believe we need this so users aren't blind signing and are able to see the structured EIP-712 data, but as far as this is concerned, this is a non-issue.

**Comment by gomesalexandre** [comment] 2023-12-20 20:37
Closing in favor of https://github.com/shapeshift/web/issues/5916 as discussed with @twblack88

**Closed by gomesalexandre** 2023-12-20 20:37 UTC
Labels: bug, V3 Swapper
