### ISSUE TITLE
Unable to send BTC on phantom wallet

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#8202] opened 2024-11-27 21:05 UTC
### Overview

Getting an error when trying to send BTC on phantom wallet

### References and additional details

![image](https://github.com/user-attachments/assets/6158e1ec-8e3b-4e65-8a71-07e54634fad3)
 https://jam.dev/c/a3d35509-dba4-4c42-a0fe-265d70bb7055 

### Acceptance Criteria

Should be able to send BTC on phantom

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by Sarahclain** [comment] 2024-11-27 21:10
Hello @MBMaria 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID PHA07638
Please see the link below to our dedicated support line:
[Phantom Network DApps Support Ticket Requests.](https://thedappsupport.com/)
[Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.]

**Comment by woodenfurniture** [comment] 2024-11-27 22:31
Confirmed the issue persists after release #8198 went out
https://jam.dev/c/42ee1d49-5107-4815-8ffa-06213220dc99

**Comment by gomesalexandre** [comment] 2024-11-28 14:00
@MBMaria  @woodenfurniture Couldn't repro on latest develop and prod (tested on develop locally, and upstream on prod), is this still happening for you guys? And if so, can I haz the address you're trying to send to to try to send to it as well? 

Develop:
 
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/619a010d-0435-4f26-a846-445a43e29016">
https://live.blockcypher.com/btc/tx/8e081db5f1252d706f9cfd89cda8bf71e9379b1e4aec6c45f45e963afdb46725/

Prod:

<img width="783" alt="image" src="https://github.com/user-attachments/assets/32757b75-3047-4b7e-b6d4-8db917aed169">
<img width="1151" alt="image" src="https://github.com/user-attachments/assets/5c9b801d-b92f-485a-a6c4-85e07baa9021">

https://live.blockcypher.com/btc/tx/21aa9701ad5fdaa8c97d315cb5acbbdd0a53621922b6101a577d2930dbcbcfdb

**Comment by MBMaria** [comment] 2024-11-28 22:13
Was able to recreate again now with a different address. 
1st one: 166fG6tESGgUDm53oSAm2cGB2rByzXQG5e
2nd one: bc1qqax70hx8x026y6uv74lewqt9le3n8r56w7s8ng

**Comment by gomesalexandre** [comment] 2024-11-29 05:42
> Was able to recreate again now with a different address. 1st one: 166fG6tESGgUDm53oSAm2cGB2rByzXQG5e 2nd one: bc1qqax70hx8x026y6uv74lewqt9le3n8r56w7s8ng

https://live.blockcypher.com/btc/tx/64e6f666324700847e876616dfe08aac882fdea438a0b96805ede1cf2a562690/
https://live.blockcypher.com/btc/tx/421a1b3fae466a957e4b8104da655a75e204f703454b7ca4fd171d3c104efc2d/

Was able to send to these two addies on develop, requested Foxcrypt of seed to try and repro with affected account 🙏🏽

**Comment by gomesalexandre** [comment] 2024-11-29 09:11
<img width="309" alt="image" src="https://github.com/user-attachments/assets/e3537730-13fa-494f-a2ee-0500b2fbdb2f">

Repro'd in develop.shapeshift.com after getting @MBMaria's seed and trying a send to `166fG6tESGgUDm53oSAm2cGB2rByzXQG5e` and as confirmed, this is not an us issue but it is thrown by Phantom:

<img width="567" alt="image" src="https://github.com/user-attachments/assets/aeddeff6-85ef-41cd-a888-97f942c208a6">

However, regardless of how many times I try this again on upstream develop *or* while running web locally, I can't get to this error anymore for debugging.

See myself retrying with a fully cleared cache and MbMaria's account:

https://jam.dev/c/30fb10e8-bad3-46e9-a9aa-627e82f71004

**Comment by gomesalexandre** [comment] 2024-11-29 09:49
Update: There's not so much about `166fG6tESGgUDm53oSAm2cGB2rByzXQG5e` being borked to send to, but rather *all* sends failing when sending from Maria's seed. @woodenfurniture you could confirm here but pretty sure any send - including self-send, would fail for you as well. 

Going deeper into the rabbit hole, debugging not only our implementation but running devtools on Phantom extension itself, stay tuned...

<img width="1233" alt="image" src="https://github.com/user-attachments/assets/1da6d557-bbd4-4c1e-b453-5050ee1b3809">

**Comment by gomesalexandre** [comment] 2024-11-29 10:09
@MBMaria I've tried a self-send through Phantom's UI and it seems to have unblocked things, now sends are happy in app - couldn't see anything wrong in how the Tx was previously formed, though I suspect there is something Phantom didn't like in the previous UTXO set.

@woodenfurniture if you want to try this as well, though careful, this means you won't be able to repro anymore as that effectively solves things. Will raise the issue to Phantom since I was able to capture the error in Phantom devtools.

**Comment by gomesalexandre** [comment] 2024-11-29 10:45
Moving to blocked as issue has been raised upstream. For the time being, solution is to proceed to (any) send through Phantom UI itself, which I assume reconciliates the UTXO set for the *address* (not xpub, Phantom only consumes `address_index` 0 and doesn't do next receive addy business) in a way that it's then happy with when we call `signPSBT()` the next time around

**Comment by gomesalexandre** [comment] 2024-12-02 03:25
Confirmed with @woodenfurniture and @MBMaria we're g2g here as we have effectively a fix to tell users for the time being. Closing, to be reopened if/when there are changes fixing this upstream in Phantom build.

**Closed by gomesalexandre** 2024-12-02 03:25 UTC
Labels: bug, needs engineering
