### ISSUE TITLE
Unable to deposit into BCH saver vault 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5807] opened 2023-12-07 21:44 UTC
### Overview

When trying to deposit into BCH saver vault, getting the error" Transaction Failed"

### References and additional details

1) Log into app.shapeshift and connect to wallet of choice
2) Navigate to Earn page and select BCH saver vault
3) Enter flow to deposit and broadcast the transaction
4) Note that the error pops up "Transaction Failed"
![image](https://github.com/shapeshift/web/assets/100157997/fa37adb2-3f22-40db-8a60-6a7abdb36231)
![image](https://github.com/shapeshift/web/assets/100157997/9a5a049f-c25c-413a-acc1-f349e7e8cdd6)
![image](https://github.com/shapeshift/web/assets/100157997/5bfe536e-b75e-40ad-8c34-31883dfb197d)

### Acceptance Criteria

Should be able to deposit into BCH saver vault

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment] 2023-12-21 08:39
Current debugging:

 ```
gomes — Yesterday at 11:20 PM
Prod also failed on me for the same reason - regular sends are happy and so is reconciliation though so the node is somehow not happy with this precise send (the final one for savers deposits)
```




![Image](https://github.com/shapeshift/web/assets/17035424/531df441-f802-48fb-b4e0-3607e5541069)


`/api/v1/send` is failing on us with a 520. Reconciliation Tx that's broadcasted before that is somehow happy. Not sure if there's something in the deposit Tx which is built which is currently wrong because of upstream shenanigans, as we haven't changed anything ther recently, or if our send endpoint is rugging us. Will continue investigating - if it's the latter, no web change is going to be able to fix this, though that would be weird as the previous reconciliation Tx is working.

**Comment by gomesalexandre** [comment] 2023-12-21 09:17
Confirmed our built Tx is looking sane, compared against a THORSwap Tx which was broadcasted fine.
Moving this to blocked, as this looks to be caused by our node currently struggling with Txs with OP_RETURN_DATA Txs - regular sends (i.e without `OP_RETURN_DATA`) are unaffected.

Confirmed with a monkey patch without `OP_RETURN_DATA` (effectively burning money since the Tx cannot be identified by THOR) and was able to proceed with the send

![Image](https://github.com/shapeshift/web/assets/17035424/589a338f-aaea-42ae-ba31-ab34d899ebb5)

**Closed** 2024-01-03 07:44 UTC
Labels: bug, needs engineering
