### ISSUE TITLE
Keepkey's Unable to Trade ETH - ERC-20's

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#4518] opened 2023-05-17 20:34 UTC
### Overview

Currently, Keepkeys are unable to trade ETH / ERC-20s and the payload error comes up as "message"insufficient funds for gas*price + value" when it fails to broadcast. 

Recreation Steps:
1. Attempt an ERC-20 trade
2. Notice that it dead clicks and never broadcasts the transaction

### References and additional details

N/A

### Acceptance Criteria

Keepkey users should be able to trade ERC-20's and ETH

**Comment by woodenfurniture** [comment] 2023-05-18 20:09
@0xApotheosis lets triage today

**Comment by 0xApotheosis** [comment] 2023-05-18 20:58
@tshifty I attempted to replicate this today, but my transactions went through successfully when using KeepKey.

Successful transactions:

1. https://etherscan.io/tx/0x0c6bae2ae59e9921d5a8a374abb334f7913a30dd983e84b3aad3263af152d6ff
2. https://etherscan.io/tx/0x7db177228f86bee962927c4d34a42fca1f80038eb8e22e93f43d73d3dfadfb84

Could you please add more detail on how to replicate?

**Comment by woodenfurniture** [comment] 2023-05-18 21:26
Its likely the issue is specific to one of the swappers and the error message reported usually stems from a lowball gas estimate in the quote. 

If we can get a screen recording/screenshots of the issue (with expanded swapper selection UI) that would be ideal so we can. try to repro

**Comment by woodenfurniture** [comment] 2023-05-19 00:53
I just found a case where this may be happening - lifi sometimes requires balance of the fee asset (ETH) to cover protocol fees. If there is only sufficient balance for the network fee but not the protocol fee, the current production app would allow trades through the would fail when being confirmed. 

This is fixed in this PR
https://github.com/shapeshift/web/pull/4528

**Comment by tshifty** [comment] 2023-05-19 20:13
It happens when trying to trade an ERC-20 as the input

**Comment by tshifty** [comment] 2023-05-19 20:21
It happens when you try to do a donation and works without it btw

**Comment by twblack88** [comment] 2023-05-22 22:38
Likely solution is to disable the donations for KK users thanks to @0xApotheosis . we should band aid it, and as a follow up @willyogo and @twblack88 to go deeper on research

looking at :
- do gas prices match what we see from other aggregators? if so then that is the market can't resolve.
- how do aggregators do payload management? might we be missing some gas optimized pattern?

**Comment by 0xApotheosis** [comment] 2023-05-23 22:30
@twblack88 the bandaid was merged and deployed yesterday: https://github.com/shapeshift/web/pull/4539

**Comment by purelycrickets** [comment] 2023-08-30 21:29
merged

**Closed by purelycrickets** 2023-08-30 21:29 UTC
