### ISSUE TITLE
rFOX reward history capturing and displaying non reward txs in the reward tx history zection

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7229] opened 2024-06-25 19:00 UTC
### Overview

Currently in develop, the rFOX rewards tx history logs are capturing non reward txids as reward txs. 

### References and additional details

https://discord.com/channels/554694662431178782/1252410161163931730/1255234233543164037 discord report of issue

![Screenshot 2024-06-25 at 12 55 48 PM](https://github.com/shapeshift/web/assets/94998097/84c1c471-058e-4a04-908b-ea3d2aa46cbb)
![Screenshot 2024-06-25 at 12 51 17 PM](https://github.com/shapeshift/web/assets/94998097/24d8e5dd-f039-45e6-8fe7-ec14900bfa37)
Tests of BTC and ETH sends unrelated to rFOX showing up in rFOX rewards tx log

### Acceptance Criteria

rFOX rewards tx log only captures txs related to rewards.

**Comment by gomesalexandre** [comment] 2024-06-25 19:56
Duplicate of https://github.com/shapeshift/web/issues/7215 - this isn't a bug, rFOX dashboard isn't yet wired up, this is just a placeholder for now.

**Closed by gomesalexandre** 2024-06-25 19:56 UTC
Labels: needs engineering

**Comment by 0xean** [comment] 2024-07-01 22:20
ref https://github.com/shapeshift/web/issues/7281
