### ISSUE TITLE
QR scanner on mobile browser not working 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5391] opened 2023-10-03 04:50 UTC
### Overview

The QR scanner when connected to shapeshift on mobile browser is not working. (mobile app is working fine) 

### References and additional details

1) Log into app.shapeshift on mobile browser
2) Select the QR code
3) Note comes up with "An error occurred"
![image](https://github.com/shapeshift/web/assets/100157997/6ab03eed-804c-46df-9e86-d8a7f0bcc6dc)

### Acceptance Criteria

Should be able to use QR scanner on mobile browser

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment] 2024-03-05 16:51
@MBMaria Which browser was that tested with?
On iOS, other browser using the webkit engine *may* have issues accessing camera, see https://issues.chromium.org/issues/40533574 which has been open just about forever - I tested myself on gome with some added debugging.

- Safari was happy
- Orion is throwing permission errors
- Chrome on the other hand is happy

Closing this with the same unfortunate answer to use Safari (or Chrome, which has been confirmed working here) as the MM deep-linking issues that still exist on some browsers after yesterday's bugfixes: this is due to browsers discrepancies, and the native browser (Safari on iOS, Chrome on Android) just tends to work better for certain features because of implementation discrepancies and issues with Webkit. 

As a sanity check, you can try https://scanapp.org which uses the same library as us and will surface the errrors there

**Closed by gomesalexandre** 2024-03-05 16:51 UTC
Labels: bug, mobile, needs engineering
