### ISSUE TITLE
Unable to fetch rates for all swapper protocols when trading between acounts

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#4966] opened 2023-07-21 22:07 UTC
### Overview

When using swapper and trading between Account 0 and 1, a user in unable to fetch rates. 

### References and additional details

When the Thornode went down this was much more apparent as the only rates being fetched for swaps between different accounts currently are thor and osmo rates.  

![Screenshot 2023-07-21 at 12 30 56 PM](https://github.com/shapeshift/web/assets/94998097/29ad65e2-ce3b-4bb1-8ca3-eeda52aaa10d)

### Acceptance Criteria

Trading between different accounts in swapper (account 0 > account 1) provides accurate rates for all available swapper protocols.

**Comment by 0xean** [comment] 2023-12-11 20:35
This may be related to certain swappers not support a different final address for the swap, but this is not apparent to the user and we should give them better messaging about the issue.

**Comment by 0xApotheosis** [comment] 2023-12-12 00:13
This is not a bug, but rather a lack of functionality.

- Some swappers, such as 0x, do not support cross-account swaps.
- THORChain does, and this is currently the only swapper that does supports it, and has the wiring to use it.
- 1inch allows it via their API, so I've made a PR that enables cross-chain swaps for our 1inch swapper, too: https://github.com/shapeshift/web/pull/5834 (which will close this ticket).

I'll also investigate doing the same for LiFi, though @woodenfurniture might have some info on why this isn't already turned on there.

**Closed** 2023-12-12 09:26 UTC
Labels: bug, needs engineering, needs product, V3 Swapper
