### ISSUE TITLE
Attempting an avax trade when MM is not connected to Avalanche network (from trade page) gives 'Something went wrong' error

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3547] opened 2023-01-02 01:35 UTC
### Overview

When trying to do an avax trade on MM from the trade page where avalanche is not a network on MM wallet, it allows you to confirm and trade but then gives a something went wrong error. There is no pop up from MM to add the avalanche network.

### References and additional details

1) Log into app.shapeshift and connect to MM wallet
2) Log into MM and make sure that avalanche is not an available network
3) In app.shapeshift, navigate to the Trade page
4) Create an avax trade (ie avax to weth on avalanche) 
5) Select confirm and trade and notice the 'Something went wrong error' appears.
![image](https://user-images.githubusercontent.com/100157997/210189833-004654ee-66fb-4f16-ad65-ab161f6b322f.png)
![image](https://user-images.githubusercontent.com/100157997/210189844-e3b904d6-8017-43df-b311-51a690a60fef.png)

### Acceptance Criteria

when doing an avax trade and avalanche network is not on MM, then a pop up should appear to prompt you to add the avalanche network

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment] 2023-01-03 20:55
@MBMaria I wasn't able to reproduce this locally / in prod, could you confirm whether or not you can still reproduce it?

However, while testing this, I've noticed some behavior where the quote is lost after adding the chain, meaning that:

- The symbol is lost

<img width="404" alt="image" src="https://user-images.githubusercontent.com/17035424/210435101-0f8119eb-3c7d-4923-8d75-994116ffbe64.png">

- The approval step never completes despite on-chain completion

Let's use this issue to tackle this 🙏🏽 

@0xApotheosis FYI looks like this is causing it:

https://github.com/shapeshift/web/blob/f70aec029c60712951e6d2b93e47b78a0dd3d4f5/src/components/Trade/hooks/useDefaultAssets.tsx#L52

We set the default assets when changing chains, which in turn run this effect and resets the quote to `undefined`:

https://github.com/shapeshift/web/blob/f70aec029c60712951e6d2b93e47b78a0dd3d4f5/src/components/Trade/Trade.tsx#L61

I think unless we're on trade input route (i.e we already have a quote and are in a happy path, meaning the quote isn't going to change, and whichever EVM network change just happened the wallet is going to be handled by the wallet chain switch logic), this effect should never run, WDYT?

**Comment by 0xdef1cafe** [comment] 2023-05-09 21:08
@gomesalexandre @MBMaria can we please close this out if it's fixed? we haven't had network switching issues in a long time

**Comment by 0xdef1cafe** [comment] 2023-05-09 21:09
as discussed with @gomesalexandre this is fixed

**Closed by 0xdef1cafe** 2023-05-09 21:09 UTC
Labels: needs engineering
