### ISSUE TITLE
upgrade to create react app 5

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#582] opened 2021-12-16 04:54 UTC
chore but nice to get on top of now before our custom webpack config diverges too much and we can never track upstream again

@reidrankin might be suited to this as he understands why we needed to use react-scripts-rewired in the first place for unsupported features

**Comment by reidrankin** [comment] 2021-12-21 02:34
closing as dupe of #589 since that one's got more detailed AC

**Closed by reidrankin** 2021-12-21 02:34 UTC
