### ISSUE TITLE
Avax 0x Trades not updating correctly in trade modal 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4887] opened 2023-07-04 22:54 UTC
### Overview

When completing a 0x trade with Avalanche, the trade modal is not updating to complete after the transaction has been confirmed on the blockchain. The tx in the Recent Transactions is showing as failed or it fails to appear. Hard refresh seems to fix the issue.

### References and additional details

1) Log into app.shapeshift and connect to shapeshift or mm
2) Navigate to trade page and set up a 0x avalanche trade
3) Confirm trade and note that the trade modal does not update
4) Click the txid and note that the transaction says successful on chain
5) Select the tx under Recent Transactions (if there) and note it says Failed transaction. 
![image](https://github.com/shapeshift/web/assets/100157997/0bcf151e-072a-4f54-a8e6-6ea7bf3a0ccd)
![image](https://github.com/shapeshift/web/assets/100157997/581656e3-3128-443d-9509-2d8c9b849f91)

https://github.com/shapeshift/web/assets/100157997/79604faf-2531-4b17-9ee8-74a5cf5893e8

### Acceptance Criteria

Trade modal should update after trade has completed and transaction history should represent correct status of trade

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment] 2023-07-05 10:43
Managed to reproduce this, though while investigating this, noticed that unchained is drunk for Avalanche balances, see unchained vs. Snowtrace

<img width="477" alt="image" src="https://github.com/shapeshift/web/assets/17035424/7fcb2920-f8e0-432f-b4e8-fbdd487a08e0">
<img width="399" alt="image" src="https://github.com/shapeshift/web/assets/17035424/84d6eab9-600a-4cd2-aaef-a876d2f16ee4">

@kaladinlight ^^

**Comment by gomesalexandre** [comment] 2023-07-05 11:39
Looks like the unchained ws is borked for Avalanche, managed to repro with dev and prod envs - Txid never gets upserted from ws message here

**Comment by gomesalexandre** [comment] 2023-07-24 19:59
Avalanche node is happy again, I was able to perform Avalanche trades to completion - Tx history is happy as well

@MBMaria can you confirm this is fixed and close this? 🙏🏽 

<img width="1408" alt="image" src="https://github.com/shapeshift/web/assets/17035424/c552cf53-ecd4-4a66-abba-ccf54ffcd3c0">
<img width="1406" alt="image" src="https://github.com/shapeshift/web/assets/17035424/723068ea-409a-4e19-a67f-6721e6db6342">
<img width="1405" alt="image" src="https://github.com/shapeshift/web/assets/17035424/2df880a4-1f18-4834-a714-9615afc02008">

**Comment by purelycrickets** [comment] 2023-07-28 21:36
Can confirm this is working now.

**Closed by purelycrickets** 2023-07-28 21:36 UTC
Labels: needs engineering
