### ISSUE TITLE
Not enough BTC to cover gas error but user has more btc in wallet than fee amount stated

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7668] opened 2024-08-30 23:16 UTC
### Overview

A user has deposited into BTC LP and when he selects the withdraw button he gets an error saying not enough btc to cover gas. Fees stated are much less than the amount in his wallet. Not sure if there are other thresholds that we have implemented so that the funds don't get burned or if this is an actual issue

### References and additional details

![image](https://github.com/user-attachments/assets/21836c81-2a95-4064-b538-9557d3ab4469)
![image](https://github.com/user-attachments/assets/12425b9e-54e4-4646-aeec-afd9e110e7dd)

### Acceptance Criteria

if balance is higher than fees listed then should be able to withdraw

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment] 2024-09-23 22:34
dupe of #7778

**Closed by 0xean** 2024-09-23 22:34 UTC
Labels: bug, needs engineering
