### ISSUE TITLE
Mobile users are prompted to enter a non existent password (not biometrics) after a cache clear

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7333] opened 2024-07-08 21:45 UTC
### Overview

Currently in Production in the mobile app, when a user attempts a cache clear, the mobile app asks for a password to unlock the wallet.  Mobile users are never prompted to enter these passwords and all mobile apps should be unlocked via biometrics. 

### References and additional details

<img width="265" alt="Screenshot 2024-07-08 at 3 39 47 PM" src="https://github.com/shapeshift/web/assets/94998097/3797e6eb-e433-4005-8bf2-763fec9e2228">
Mobile device experiencing the password prompt after performing a clear cache. 

### Acceptance Criteria

Mobile users should always be prompted with biometric unlock when asking for user unlock.  This should be remedied in the clear cache flow where it is currently using passwords.

**Comment by NeOMakinG** [comment] 2024-07-08 21:58
Isn't it a duplicate of https://github.com/shapeshift/web/issues/6704 with more informations?

**Closed** 2024-07-11 06:48 UTC
Labels: mobile, needs engineering
