### ISSUE TITLE
Keepkey with Passphrase on an older firmware version cannot connect on app.shapeshift.com

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#1565] opened 2022-04-23 02:29 UTC
### Overview

After entering the pin for a KK with a passphrase on an older firmware version, it asks for the passphrase. At that point the front end hangs and the keepkey does not get past the "Waiting for Passphrase..." screen. This is due to the KK not being updated. Updating fw + bl fixes the issue

### References and additional details

1) Connect KK with Passphrase on app.shapeshift.
2) Enter PIN. 
3) Enter passphrase. 
4) See hanging front end. 
5) See message on KK. 

**only happens if KK is not updated

### Acceptance Criteria

Should be able to connect to wallet with pin and passphrase.
**needs product input on the expected message/flow

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment] 2022-04-23 02:43
@DiggyDiggy2 how does your team want the site to handle this issue?

**Comment by MBMaria** [comment] 2022-04-23 02:46
Closed accidently. Sorry about that.

**Comment by DiggyDiggy2** [comment] 2022-04-26 16:02
We are currently trying to replicate this.

**Comment by 0xdef1cafe** [comment] 2022-04-28 16:21
@MBMaria have you upgraded the firmware on this device yet? if not, could you please physically get the device to @0xApotheosis to repro and diagnose?

**Comment by Neverwas-dev** [comment] 2022-04-28 16:38
@DiggyDiggy2 I worked with @MBMaria and @Lychbot yesterday on this and was unable to recreate on my KeepKey that is on 
<img width="854" alt="image" src="https://user-images.githubusercontent.com/95000549/165801678-aeb3922c-ea55-44de-b1b7-ecb3a95ba632.png">

**Comment by Neverwas-dev** [comment] 2022-04-28 22:42
During testing today I was able to recreate this with regularly and may have a possible root cause. I have since tested with @MBMaria and @Lychbot and we can all recreate with the following steps and this is for both old versions of firmware and bootloaders and the most recent.
Recreation steps
1. Log in to a different wallet and switch to KeepKey wallet
2. Enter your pin code
3. when prompted to enter phasePhrase either hit continue without entering or enter one
4. the keepkey screen will be stuck on enter phase phrase and will not continue to load wallet
5. To clear hard refresh the web page

**Comment by 0xApotheosis** [comment] 2022-04-29 00:06
I can use @MBMaria's KeepKey to work through this.

**Comment by MBMaria** [comment] 2022-04-29 00:27
My keepkey is updated to the current bootloader and firmware. This ticket was created off a triage ticket put through by joshuAF so not sure if you will need my kk?

![image](https://user-images.githubusercontent.com/100157997/165867521-d02b3b61-01a8-4d8b-b4ef-b1cd61e65a4b.png)

**Comment by DiggyDiggy2** [comment] 2022-05-03 20:10
This sounds like a bug to me, with older firmware that it's just hanging. Can we just fix this so it doesn't hang on that step? @0xdef1cafe - is this something for @pastaghost or Highlander?

**Comment by 0xean** [comment] 2022-05-18 20:12
assigning to KK workstream  / @pastaghost

**Comment by pastaghost** [comment] 2022-05-18 20:14
@0xean Thanks for the ping for visibility - we'll get this in the queue right away.

**Comment by 0xdef1cafe** [comment] 2022-07-20 19:49
@markrypt0 to look at as per @pastaghost

**Comment by markrypt0** [comment] 2022-07-20 21:52
I just tested this and can confirm @Neverwas-dev's finding. The specific action causing the problem is
**Log in to a different wallet and switch to KeepKey wallet**
Otherwise it works without any problems that I can see.

The app is not initializing the keepkey when you switch wallets. This appears to be a client level problem, not really my purview. Maybe a bounty project?

**Closed** 2023-05-02 22:35 UTC
Labels: keepkey
