### ISSUE TITLE
Withdraw from Atom vault failing

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7730] opened 2024-09-11 00:15 UTC
### Overview

Getting transaction failed for a withdraw of the Atom thorchain saver vault

### References and additional details

![image](https://github.com/user-attachments/assets/1a9bb7aa-864f-44f8-b1da-55037e3a2b7d)
https://jam.dev/c/05bcf62a-63f9-4d25-94d7-6aede6227750

### Acceptance Criteria

Should be able to withdraw from atom vault

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by NeOMakinG** [comment] 2024-09-11 07:20
https://viewblock.io/thorchain/tx/6246D74F2F8E2D467B86BBA005ECD30549708AB1F5A899C59CCF9BB159284875

It worked on my side, I suspect that you did deposit 1 hour maximum before your withdraw

Starting after the fork, savers has a 1 hour lockup https://github.com/shapeshift/web/issues/7708#issuecomment-2340245479

**Comment by gomesalexandre** [comment] 2024-09-16 22:10
Duplicate of https://github.com/shapeshift/web/issues/7708 - confirmed related to newly introduced lockup time

**Closed by gomesalexandre** 2024-09-16 22:10 UTC
Labels: bug, needs engineering
