### ISSUE TITLE
Unable to get LiFi quotes for certain pairs

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#5874] opened 2023-12-15 16:46 UTC
### Overview

Currently in Production there are many pairs that do not display a LiFi quote and we get unsupported pair UI for simple trades that should have integrated routes. 

### References and additional details

![Screenshot 2023-12-15 at 9 38 08 AM](https://github.com/shapeshift/web/assets/94998097/3330678d-8a03-476c-b269-dfe046d4af34)
Unavailable on SS

![Screenshot 2023-12-15 at 9 42 59 AM](https://github.com/shapeshift/web/assets/94998097/bb36bae0-e5dd-43d2-8968-726b39fd746b)
Available on Jumper

![image-2](https://github.com/shapeshift/web/assets/94998097/7a33dc59-b93c-4ffb-8d51-913b4e91545a)
Unavailable on SS

![Screenshot 2023-12-15 at 9 45 18 AM](https://github.com/shapeshift/web/assets/94998097/79f73636-b495-4bd8-b046-c665f6f1e8b5)
Available on Jumper

The pattern of what is available and what is not for LiFi quotes is still unidentified but it appears stable coins maybe be a pattern that are affected. 

### Acceptance Criteria

Users should receive LiFi quotes for all available pairs they can from Jumper in the ShapeShift app.

**Comment by 0xean** [comment] 2023-12-15 17:16
Some of these may be due to the disabled routes, but doesn't seem to tell the whole story to describe the lack of quotes.

**Comment by 0xean** [comment] 2023-12-15 17:26
quick peak and we are getting valid routes back from lifi it appears, not sure why these aren't showing up 

```
{
  "routes": [
    {
      "id": "0xc6d006e6ccb6a4c366eb22e7f38cb1f73e71f69634ba83db306b4b4d3f04a683",
      "fromChainId": 1,
      "fromAmountUSD": "8966.16",
      "fromAmount": "4000000000000000000",
      "fromToken": {
        "address": "0x0000000000000000000000000000000000000000",
        "chainId": 1,
        "symbol": "ETH",
        "decimals": 18,
        "name": "ETH",
        "coinKey": "ETH",
        "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
        "priceUSD": "2241.540000000000000000"
      },
      "fromAddress": "0xeF678D1ad8C897c71D0a6145390a474035Db8f1f",
      "toChainId": 137,
      "toAmountUSD": "8960.01",
      "toAmount": "8958588091",
      "toAmountMin": "8895967561",
      "toToken": {
        "address": "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359",
        "chainId": 137,
        "symbol": "USDC",
        "decimals": 6,
        "name": "USD Coin",
        "coinKey": "USDC",
        "logoURI": "https://static.debank.com/image/coin/logo_url/usdc/e87790bfe0b3f2ea855dc29069b38818.png",
        "priceUSD": "1.000159060035165"
      },
      "toAddress": "0xeF678D1ad8C897c71D0a6145390a474035Db8f1f",
      "gasCostUSD": "199.76",
      "containsSwitchChain": false,
      "steps": [
        {
          "type": "lifi",
          "id": "1b6b79e3-04f0-4c26-8e41-4cd083537d84",
          "tool": "allbridge",
          "toolDetails": {
            "key": "allbridge",
            "name": "Allbridge",
            "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/bridges/allbridge.png"
          },
          "action": {
            "fromToken": {
              "address": "0x0000000000000000000000000000000000000000",
              "chainId": 1,
              "symbol": "ETH",
              "decimals": 18,
              "name": "ETH",
              "coinKey": "ETH",
              "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
              "priceUSD": "2241.540000000000000000"
            },
            "fromAmount": "4000000000000000000",
            "toToken": {
              "address": "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359",
              "chainId": 137,
              "symbol": "USDC",
              "decimals": 6,
              "name": "USD Coin",
              "coinKey": "USDC",
              "logoURI": "https://static.debank.com/image/coin/logo_url/usdc/e87790bfe0b3f2ea855dc29069b38818.png",
              "priceUSD": "1.000159060035165"
            },
            "fromChainId": 1,
            "toChainId": 137,
            "slippage": 0.005,
            "fromAddress": "0xeF678D1ad8C897c71D0a6145390a474035Db8f1f",
            "toAddress": "0xeF678D1ad8C897c71D0a6145390a474035Db8f1f"
          },
          "estimate": {
            "tool": "allbridge",
            "approvalAddress": "0x1231DEB6f5749EF6cE6943a275A1D3E7486F4EaE",
            "toAmountMin": "8895967561",
            "toAmount": "8958588091",
            "fromAmount": "4000000000000000000",
            "feeCosts": [
              {
                "name": "Integrator Fee",
                "description": "Fee shared between integrator and LI.FI",
                "token": {
                  "address": "0x0000000000000000000000000000000000000000",
                  "chainId": 1,
                  "symbol": "ETH",
                  "decimals": 18,
                  "name": "ETH",
                  "coinKey": "ETH",
                  "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
                  "priceUSD": "2241.540000000000000000"
                },
                "amount": "12000000000000000",
                "amountUSD": "26.90",
                "percentage": "0",
                "included": true
              },
              {
                "name": "Allbridge's fee",
                "description": "AllBridge fee and messenger fee charged by Allbridge",
                "token": {
                  "address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
                  "chainId": 1,
                  "symbol": "USDC",
                  "decimals": 6,
                  "name": "USD Coin",
                  "coinKey": "USDC",
                  "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png",
                  "priceUSD": "1"
                },
                "amount": "26031",
                "amountUSD": "0.03",
                "percentage": "0.0000",
                "included": true
              }
            ],
            "gasCosts": [
              {
                "type": "SEND",
                "price": "151713147120",
                "estimate": "587393",
                "limit": "930393",
                "amount": "89115240626258160",
                "amountUSD": "199.76",
                "token": {
                  "address": "0x0000000000000000000000000000000000000000",
                  "chainId": 1,
                  "symbol": "ETH",
                  "decimals": 18,
                  "name": "ETH",
                  "coinKey": "ETH",
                  "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
                  "priceUSD": "2241.540000000000000000"
                }
              }
            ],
            "executionDuration": 1290,
            "fromAmountUSD": "8966.16",
            "toAmountUSD": "8960.01"
          },
          "includedSteps": [
            {
              "id": "9d4a620b-d786-4526-a14f-328b1c3ba507",
              "type": "protocol",
              "action": {
                "fromChainId": 1,
                "fromAmount": "4000000000000000000",
                "fromToken": {
                  "address": "0x0000000000000000000000000000000000000000",
                  "chainId": 1,
                  "symbol": "ETH",
                  "decimals": 18,
                  "name": "ETH",
                  "coinKey": "ETH",
                  "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
                  "priceUSD": "2241.540000000000000000"
                },
                "toChainId": 1,
                "toToken": {
                  "address": "0x0000000000000000000000000000000000000000",
                  "chainId": 1,
                  "symbol": "ETH",
                  "decimals": 18,
                  "name": "ETH",
                  "coinKey": "ETH",
                  "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
                  "priceUSD": "2241.540000000000000000"
                },
                "slippage": 0.005
              },
              "estimate": {
                "fromAmount": "4000000000000000000",
                "toAmount": "3988000000000000000",
                "toAmountMin": "3988000000000000000",
                "tool": "feeCollection",
                "approvalAddress": "0xbD6C7B0d2f68c2b7805d88388319cfB6EcB50eA9",
                "gasCosts": [
                  {
                    "type": "SEND",
                    "amount": "100000",
                    "token": {
                      "address": "0x0000000000000000000000000000000000000000",
                      "chainId": 1,
                      "symbol": "ETH",
                      "decimals": 18,
                      "name": "ETH",
                      "coinKey": "ETH",
                      "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
                      "priceUSD": "2241.540000000000000000"
                    },
                    "price": "151713147120",
                    "limit": "200000",
                    "estimate": "200000",
                    "amountUSD": "0.01"
                  }
                ],
                "feeCosts": [
                  {
                    "name": "Integrator Fee",
                    "description": "Fee shared between integrator and LI.FI",
                    "token": {
                      "address": "0x0000000000000000000000000000000000000000",
                      "chainId": 1,
                      "symbol": "ETH",
                      "decimals": 18,
                      "name": "ETH",
                      "coinKey": "ETH",
                      "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
                      "priceUSD": "2241.540000000000000000"
                    },
                    "amount": "12000000000000000",
                    "amountUSD": "26.90",
                    "percentage": "0",
                    "included": true
                  }
                ],
                "executionDuration": 0
              },
              "tool": "feeCollection",
              "toolDetails": {
                "key": "feeCollection",
                "name": "Integrator Fee",
                "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/protocols/feeCollection.png"
              }
            },
            {
              "id": "e0a6958d-fc1e-42cb-b140-73955b27202b",
              "type": "swap",
              "action": {
                "fromChainId": 1,
                "fromAmount": "3988000000000000000",
                "fromToken": {
                  "address": "0x0000000000000000000000000000000000000000",
                  "chainId": 1,
                  "symbol": "ETH",
                  "decimals": 18,
                  "name": "ETH",
                  "coinKey": "ETH",
                  "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
                  "priceUSD": "2241.540000000000000000"
                },
                "toChainId": 1,
                "toToken": {
                  "address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
                  "chainId": 1,
                  "symbol": "USDC",
                  "decimals": 6,
                  "name": "USD Coin",
                  "coinKey": "USDC",
                  "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png",
                  "priceUSD": "1"
                },
                "slippage": 0.005
              },
              "estimate": {
                "tool": "1inch",
                "fromAmount": "3988000000000000000",
                "toAmount": "8934059845",
                "toAmountMin": "8889389546",
                "approvalAddress": "0x1111111254eeb25477b68fb85ed929f73a960582",
                "executionDuration": 30,
                "feeCosts": [],
                "gasCosts": [
                  {
                    "type": "SEND",
                    "price": "151713147120",
                    "estimate": "202393",
                    "limit": "263111",
                    "amount": "30705678985058160",
                    "amountUSD": "68.83",
                    "token": {
                      "address": "0x0000000000000000000000000000000000000000",
                      "chainId": 1,
                      "symbol": "ETH",
                      "decimals": 18,
                      "name": "ETH",
                      "coinKey": "ETH",
                      "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png",
                      "priceUSD": "2241.540000000000000000"
                    }
                  }
                ]
              },
              "tool": "1inch",
              "toolDetails": {
                "key": "1inch",
                "name": "1inch",
                "logoURI": "https://raw.githubusercontent.com/lifinance/types/main/src/assets/icons/exchanges/oneinch.png"
              }
            },
            {
              "id": "23467da8-ff19-4e16-b047-e5e25d519a2d",
              "type": "cross",
              "action": {
                "fromChainId": 1,
                "fromAmount": "8889389546",
                "fromToken": {
                  "address": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
                  "chainId": 1,
                  "symbol": "USDC",
                  "decimals": 6,
                  "name": "USD Coin",
                  "coinKey": "USDC",
                  "logoURI": "https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png",
                  "priceUSD": "1"
                },
                "toChainId": 137,
                "toToken": {
                  "address": "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359",
                  "chainId": 137,
                  "symbol": "USDC",
                  "decimals": 6,
                  "name": "USD Coin",
                  "coinKey": "USDC",
                  "logoURI": "https://static.debank.com/image/coin/logo_url/usdc/e87790bfe0b3f2ea855dc29069b38818.png",
                  "priceUSD": "1.000159060035165"
                },
                "slippage": 0.005,
                "destinationGasConsumption": "0",
                
```

**Comment by woodenfurniture** [comment] 2023-12-18 01:53
if jumper is showing a lifi quote and we aren't, here are some possible reasons why:
- we have have 3 bridges blocked due to unsupported fee model
- we dont have multi-hop routes enabled currently
- timeout on the quote api in react. We have a 20s limit on the quote generation which includes gas requests. If this exceeds our timeout the swapper wont return any quotes.
 
point #3 does rely on the node to generate a qutoe because it includes gas estimation. Most of the time it times out is due to slow gas estimation

**Comment by 0xean** [comment] 2023-12-18 10:52
> we dont have multi-hop routes enabled currently
@woodenfurniture I assume a swap then a bridge is considered multi-hop? If so, that probably makes sense looking at their UI as the explanation for us not showing these paths.

**Comment by woodenfurniture** [comment] 2023-12-18 23:19
So far I'm unable to reproduce the issue - one of the pairs above is actually unsupported in our current app (see payload), likely due to blocked bridges and/or lack of multi-hop support. 

Please note that an available quote also request the whitelisted bridges are online at the time of the quote, and that we're not guaranteed to return the same quotes as jumper due to the factors outlined above and in this comment:
https://github.com/shapeshift/web/issues/5874#issuecomment-1859419659

This pair is actually correctly unsupported:
![Image](https://github.com/shapeshift/web/assets/125113430/1ee37ee5-73f0-4ebd-921e-beb81b8be3f6)
![Image](https://github.com/shapeshift/web/assets/125113430/f46e1570-23a3-4781-a334-6a4a6d1ecf22)

This pair worked - likely a transient issue when reported:
![Image](https://github.com/shapeshift/web/assets/125113430/f73b76ce-9a6c-4a6d-a57c-8c507ed023b9)

**Comment by 0xean** [comment] 2023-12-18 23:36
thanks @woodenfurniture - closing as known / expected behavior.

I think our current path of collecting these failures and determining if we need to add support for different routes based on that data is the correct approach from here. 

cc @purelycrickets

**Closed by 0xean** 2023-12-18 23:36 UTC
Labels: bug, needs engineering
