### ISSUE TITLE
rFOX freezes for Ledger users who have not added ARB network to the app

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7374] opened 2024-07-15 21:59 UTC
### Overview

Currently in Production, Ledger users attempting staking deposits to rFOX that do not have the ARB network added to the app will cause the rFOX page to load indefinitely.   

### References and additional details

Jam of the issue: https://jam.dev/c/e28fcc1f-8260-4186-8a27-7f6f665989c2

### Acceptance Criteria

A CTA to add the required accounts to ledger users attempting to access the rFOX page that do not have all of the required accounts currently added to the app.

**Comment by 0xean** [comment] 2024-07-15 22:15
Use the ack flow for ledger app

**Comment by 0xean** [comment] 2024-07-15 22:15
#7339 for reference

**Comment by woodenfurniture** [comment] 2024-07-19 03:12
See https://github.com/shapeshift/web/issues/7339 generic solution this

**Comment by NeOMakinG** [comment] 2024-08-09 14:42
I took some time thinking about the proper way to fix this issue

I feel like the solution proposed on the ticket is not the one we really want

As a user, even if I don't have the ethereum app launched on my ledger, I could be interested to access this page (seeing rFOX stats, FAQ...)

![image](https://github.com/user-attachments/assets/eb2fd59c-6429-4855-997d-fa368c1d9cb9)

I would empty the wallet-related values currently as skeletons and use the ledger ACK when trying to click on any asset-related buttons such as deposit, claim...

wdyt @shapeshift/product ?

**Comment by gomesalexandre** [comment] 2024-08-09 16:20
> I took some time thinking about the proper way to fix this issue
> 
> I feel like the solution proposed on the ticket is not the one we really want
> 
> As a user, even if I don't have the ethereum app launched on my ledger, I could be interested to access this page (seeing rFOX stats, FAQ...)
> 
> ![image](https://private-user-images.githubusercontent.com/14963751/356650892-eb2fd59c-6429-4855-997d-fa368c1d9cb9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjA0MDAsIm5iZiI6MTcyMzIyMDEwMCwicGF0aCI6Ii8xNDk2Mzc1MS8zNTY2NTA4OTItZWIyZmQ1OWMtNjQyOS00ODU1LTk5N2QtZmEzNjhjMWQ5Y2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDE2MTUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjOWFiZTVmZmQ5ODIwOWM3NmNiNzE0ZDQ4YTQyMzIwZWVjZDU3ZTE0NDJhMjY0YjdhZDZlODIwNDZkYjQ3N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xuNZKkCqN5lD0dSzlXMf_K4nYAn21PPXHFENIjsD0U0)
> 
> I would empty the wallet-related values currently as skeletons and use the ledger ACK when trying to click on any asset-related buttons such as deposit, claim...
> 
> wdyt @shapeshift/product ?

FYI @NeOMakinG you shouldn't need the app open - that's irrelevant to accounts pseudo-derivation: if you ever derived those accounts on-device previously, these will still be present in the app and we'll just use the pubkey as-is (for account-based chains, i.e both RUNE and EVM chains) and unchained with xpub (not on-device) derivation for UTXOs.

re: zeroing out values, absolutely agree on that, that's an actual bug here.

re: ack, what would be the ack/CTA there?  Looks like the current flow ("Chain not supported by wallet") already captures the "No account connected for that chain" flow to some extent, and the remaining bits would be to
1. handle the app not open flow by either *attempt*ing on-device derivation (or check for Ledger app open same we're doing in Account Management modal)
2. possibly improve the messaging here for the case of wallet supporting the chain, but no accounts present (see `useWalletSupportsChain` logic WRT runtime support)

**Comment by reallybeard** [comment] 2024-08-13 14:33
@gomesalexandre @NeOMakinG 
Okay just want to make sure I understand the proposed solutions here:

1. We will 0 out the values so it doesn't look like its just stuck in a loading state.
2. We will add the ack to connect the ARB app on ledger only at time of singing.
3. We need to come up with possibly a better error for "Chain not supported by wallet". (or some way to educate the user on what the problem is). 

#1 and #2 both seem to make sense to me.

**Comment by gomesalexandre** [comment] 2024-08-13 14:47
Correct for 1. and 2. @reallybeard!

And 3. is indeed the one which we need to iron out some more, if we believe the current copy/flow isn't clear enough for users. Think a tooltip could be all we need?

**Comment by twblack88** [comment] 2024-08-13 15:30
No3 tooltip makes sense

"No accounts found for %{chain}. You may need to add the app to your ledger device, open the app on your device, or add accounts with balances"

**Comment by 0xean** [comment] 2024-08-19 23:18
AC:
1. Fix loading state when arb accounts aren't available. We will 0 out the values so it doesn't look like its just stuck in a loading state.
2. We will add the ack to connect the ARB app on ledger only at time of singing. Reuse flow for https://github.com/shapeshift/web/issues/7339

**Comment by 0xean** [comment] 2024-08-19 23:18
cc @NeOMakinG we discussed during weekly sync and wanted to clarify the outcomes expected for this ticket (listed above). Please let us know if you have more questions on what is needed to close this ticket.

**Comment by gomesalexandre** [comment] 2024-08-21 01:24
FYI @NeOMakinG: just authored https://github.com/shapeshift/web/pull/7578 as groundwork for all Ledger acks as part of  #7567 - the way our flow currently is across the app makes it so fees estimation will fail and users aren't able to continue to signing time given fees estimation fail.

This PR will ensure all affected areas (DeFi providers, RFOX, LP) now bypass on-device address derivation for Ledger when estimating fees, meaning users will be able to continue all the way up to signing time, where we'll be able to implement the Ledger open app gate.

**Closed** 2024-08-21 22:31 UTC
Labels: bug, needs engineering
