### ISSUE TITLE
Messaging/alert for not enough native token gas for amounts close to max

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#6047] opened 2024-01-18 20:38 UTC
### Overview

Currently in production, when selecting an amount that is close to, but not the max amount of an asset a user gets not enough ASSET.ASSET for gas. 

Sending some amount less than very close to the available balance will result in a successful trade (if it is above the minimum) 

Displaying to the User an amount of balance, and then not allowing them to interact with the balance in full has caused support tickets and a bad user experience for those transacting in small amounts and wishing to use their full balances in any transaction. 

### References and additional details

https://github.com/shapeshift/web/assets/94998097/eec5195c-f0fc-49ca-a227-e3f07b18ed05

### Acceptance Criteria

Could we possibly allow a user to send all of their balance and subtract the gas after they have selected the full amount?  

Man this feels like a feature request for Send Max. 

Still gonna keep it as a ticket.

**Comment by woodenfurniture** [comment] 2024-01-18 21:10
This very use case was conflated with the "max" button functionality which ended up as a Rube Goldberg machine that had to fetch multiple quotes for a given swapper:
* one to determine the fees
* another to determine the quote using the input amount minus the fees from the previous quote

The issue is that network fee fluctuations were causing trade failures. We added a multiplier on the fee to allow for some fluctuations but it always meant balance was left over in the account, hence "send most" meme in product discussions.

I strongly recommend we avoid this

**Comment by 0xean** [comment] 2024-01-18 21:55
> Man this feels like a feature request for Send Max.

if it walks like a duck...

**Comment by 0xean** [comment] 2024-01-22 20:21
per conversation on 1-22-24 product will look at error messagin to other UX to help user undertand

**Comment by twblack88** [comment] 2024-07-16 21:02
Hah, the ole send max of native asset. I think the solution is, sadly, none.

1. Operations writes a nice macro with product to explain why we're different. Decentralized and multiple quotes. Inherently, we can't tell you the max of the native token minus the quote until we...have the quote. 
2. Closing because this can't really solve with UX and messaging.

From the product lens it should "just work" aka it gives you the maximum amount when you click on it. We could get creative with optimistic quoting if we have one protocol but we have like 4 swappers and will add more too.

**Closed by twblack88** 2024-07-16 21:02 UTC
Labels: needs product, low priority
