### ISSUE TITLE
xDEFI fell over

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#6319] opened 2024-02-28 04:43 UTC
### Overview

xDEFi 
- battles with other wallets for dominance when it should eb singularly triggered to connect
- fails silently without having console open
- already has this weird error before even trying to connect. 

### References and additional details

https://www.loom.com/share/c4fb3ae2eb454e09b425723a7a7ecad4?sid=c36a171b-c30b-4260-9d8e-a48a897488f5

### Acceptance Criteria
- Connecting with xdefi triggers xdefi only no need to shut off other extensions
if not
- Triggers `walletProvider.xdefi.errors.multipleWallets` in connext.tsx earlier in process and alerts user to deactivate other extensions
- no more hitting pair twice.

**Comment by gomesalexandre** [comment] 2024-02-29 15:32
A possible contender for spiking into [EIP6963](https://eips.ethereum.org/EIPS/eip-6963)? Theoretically a huge lift in hdwallet, but if there's a way we can do this, that would make our lives so much easier WRT multiple wallet providers, and would have the added benefit of giving us visibility on the Zerion campaign

**Comment by 0xean** [comment] 2024-03-04 16:16
guys - we need to follow the process here, not throw random spikes into bug tickets. We have a huge backlog of work, lets follow the correct process and avoid assigning work outside of that.

**Comment by gomesalexandre** [comment] 2024-03-04 19:18
@twblack88 @0xean If the issue is simply "I cannot get XDEFI to connect when I have multiple wallets installed", let's close this, as this is not an issue and there is no way to solve it in the current state (barring specs like https://eips.ethereum.org/EIPS/eip-6963 which do bring a solution to the problem but are a big lift and not a simple "fix")

1.  `battles with other wallets for dominance when it should eb singularly triggered to connect` / `Connecting with xdefi triggers xdefi only no need to shut off other extensions
if not` not how it works unfortunately. This is a general issue of the ecosystem with multiple wallets injecting `window.ethereum`. 

XDEFI, like many other, allow you to "prioritize" it meaning it will try and hijack (by overriding it last) `window.ethereum` which "solves" this issue (prioritize whichever wallet you want to be used if they offer this option, and refresh)

<img width="408" alt="image" src="https://github.com/shapeshift/web/assets/17035424/fff10537-eeaf-435d-b193-9cc1dee51207">

2. `fails silently without having console open` not sure what you mean here but you shouldn't have to open the console as a user for this - various `window.ethereum` injectors simply do not work well when ran together, and as a user the unfortunate solution is to either use the prioritize option if available in your wallet, or uninstall others
3. `already has this weird error before even trying to connect.` assuming you mean the error when clicking on "Pair", that's working as it should, and the console errors you see are unrelated to ShapeShift, those are errors from XDEFI itself
4. `no more hitting pair twice.` / refresh: Ditto above, wallets will race to inject `window.ethereum` and it's usual to have to refresh when this changes, e.g Frame does so automatically when you inject it as MM

 

https://github.com/shapeshift/web/assets/17035424/bb4c233c-927d-4cd4-88b2-29a81018199c

**Closed by gomesalexandre** 2024-03-04 19:18 UTC
Labels: bug

**Comment by 0xean** [comment] 2024-03-04 19:29
yea, I am fine with not being able to support multiple wallets installed simultaneously. The only question I think is can we better detect this state and add better error messaging to the user so they know why its not working.  This is certainly not a high priority as compared to the other tickets we currently have open tho.

**Comment by twblack88** [comment] 2024-03-04 21:15
> better detect this state and add better error messaging to the user so they know why its not working

That's all i was tagging as well. Sorry if it came off different. 

@gomesalexandre agreed. 
1/2 noted
3 gotcha

4. see top of this comment. basically low priority could we handle better.

**Comment by twblack88** [comment] 2024-03-07 19:57
gonna open a diff ticket. i found an actual issue with xdefi which is that it needs to be paired twice. funky.
