### ISSUE TITLE
Refresh when KeepKey is connected results in disconnected wallet

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#5494] opened 2023-10-18 22:16 UTC
### Overview

When connected to app.shapeshift.com with a KeepKey and the user clicks the refresh button. The wallet becomes disconnected and the user needs to reconnect their device again. 

### References and additional details

This was first noticed in https://github.com/shapeshift/web/pull/5433#pullrequestreview-1680751902 but was reproducible in prod and seems to be a regression in an earlier release.  

### Acceptance Criteria

Refresh should still keep the device connected and a user should only have to re-enter a pin to have their device reconnected to ShapeShift.

**Comment by 0xean** [comment] 2023-12-06 22:26
@purelycrickets - just to confirm, with ledger the app stays connected?

**Comment by gomesalexandre** [comment] 2023-12-19 20:04
Stopping point on this - for debugging purposes, this is most likely a working version

https://github.com/shapeshift/web/blob/5a16052a34aea823eff29da9dc52a46b66ce0efe/src/context/WalletProvider/WalletProvider.tsx

The most likely culprit is the keyring not being properly loaded on refresh, see this line from the aforementioned diff:

https://github.com/shapeshift/web/blob/5a16052a34aea823eff29da9dc52a46b66ce0efe/src/context/WalletProvider/WalletProvider.tsx#L418

**Comment by gomesalexandre** [comment] 2023-12-20 18:32
Not a bug per se, by WebUSB/browser specs, device connection *has* to be initiated by a user action.
The fact that we had this "working" (with many bugs and caveats) at some point doesn't mean that this should be done.

By design, trying to reconnect a device on app refresh, especially when you take into consideration the ramifications of our "keyring" abstraction, makes it so trying to get this working *will* be hacky, and *will* bring regression risks to other wallets.

Furthermore, Ledger also doesn't support automagical refresh, which was not spotted as a bug, and indicates that this is not something that's expected of a hardware wallet by ops/users.

Discussed this with @twblack88 and wontfix.

**Closed by gomesalexandre** 2023-12-20 18:32 UTC
Labels: bug
