### ISSUE TITLE
First thorchain trade on fresh wallet import results in the app refreshing

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7384] opened 2024-07-17 02:12 UTC
### Overview

When importing a wallet on a fresh incognito browser , the first thorchain trade causes the app the refresh. Doesnt happen for other swappers. 
Jam recorded in release but happening in prod as well 

### References and additional details

https://jam.dev/c/05e17c79-515f-4dc4-9499-24c624fb49ae

### Acceptance Criteria

First thorchain trade should execute and not cause the app to refresh 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment] 2024-07-17 09:21
most likely a dupe of https://github.com/shapeshift/web/issues/7340 but will leave open for confimation

**Closed** 2024-07-25 22:59 UTC
Labels: bug, needs engineering
