### ISSUE TITLE
Refreshing native wallet causes the wallet to disconnect

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5042] opened 2023-08-07 06:25 UTC
### Overview

When refreshing the app when connected to native wallet, it causes the wallet to disconnect. To access wallet need to go into the wallet menu, select disconnect and then go through the process of connecting your wallet again

### References and additional details

1) log into app.shapeshift and connect to native wallet
2) Select refresh and note that the wallet will disconnect
![image](https://github.com/shapeshift/web/assets/100157997/cdb43e27-7156-42ce-b7be-e6804c900503)

### Acceptance Criteria

Refreshing the page should not cause the wallet to disconnect

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by firebomb1** [comment] 2023-08-15 11:16
Got Fixed by PR https://github.com/shapeshift/web/pull/5050 and was duplicate of Issue https://github.com/shapeshift/web/issues/5045 .

**Closed by firebomb1** 2023-08-15 11:16 UTC
Labels: needs engineering
