### ISSUE TITLE
trade complete green check mark coming up immediately

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#1747] opened 2022-05-11 20:34 UTC
### Overview

green check mark should not come up until the trade has been confirmed on chain.

was fixed here: https://github.com/shapeshift/web/pull/1378

### References and additional details

1. go to https://3202a9af.web-29e.pages.dev/ or app.shapeshift.com
2. log in with native, mm, or kk
3. arrive at the dashboard and make a trade within the trade widget on the right hand side of the screen
4. noticed that the trade complete green check mark comes up immediately even when trades are not completed on chain

### Acceptance Criteria

green check mark should not appear until trade has been confirmed on chain. 

### Screenshots/Mockups

<img width="296" alt="Screenshot 2022-05-11 151928" src="https://user-images.githubusercontent.com/99363597/167942817-552c17ab-7ed9-485e-95b9-ae9137a244a6.png">

**Comment by gomesalexandre** [comment] 2022-05-13 12:00
@wesleygravess Note that https://github.com/shapeshift/web/pull/1378 didn't fix the trade showing as completed when completed on chain after the swap, but rather the arrow showing completed in the "Confirm and Trade" step, which is indeed a behavior that came back up in latest builds, https://github.com/shapeshift/web/pull/1783 tackles it:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/17035424/168276630-8687fa14-c341-485d-849d-ea7bd6f61291.png">

The trade being shown as completed is due to us waiting for a Txid to assume completion, and said Txid exists optimistically as soon as a Tx is broadcasted on chain, no matter the completion status.

Now that we have a state machine that gives us proper Tx history, we should instead not be relying on the Txid only for completion, but rather introspect on it to get its status, which correctly shows as "pending" after broadcast:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/17035424/168277466-bfe06e39-6432-47f3-8f87-d952cae0870b.png">

And as "confirmed" when completed on chain.

**Comment by 0xean** [comment] 2022-05-18 20:38
closed as resolved.

**Closed by 0xean** 2022-05-18 20:38 UTC
