### ISSUE TITLE
Uptick in need to clear cache to detect recent transactions 

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7214] opened 2024-06-24 23:16 UTC
### Overview

Support has seen an uptick in the need for users to clear their cache after performing action the app should detect without needing a refresh. 

Issue seems to be chain agnostic.  Operations will be attempting more recreations to capture errors in jam.

### References and additional details

awaiting more notes from recreations 

### Acceptance Criteria

We detect all blockchain transactions without needing users to clear cache.

**Comment by 0xean** [comment] 2024-07-16 10:00
https://github.com/shapeshift/web/issues/7378

**Comment by 0xean** [comment] 2024-07-29 22:28
@kaladinlight 

"potentially related to not fetching tx history and portfolio data when using manual accounts"

**Comment by 0xean** [comment] 2024-07-29 22:37
potentially also related - https://github.com/shapeshift/web/issues/7437 - which is believed to be a regression

**Comment by 0xean** [comment] 2024-07-29 22:41
see https://github.com/shapeshift/web/blob/develop/src/context/AppProvider/AppContext.tsx#L120 for "perpetrator"

**Comment by 0xean** [comment] 2024-07-29 22:42
https://github.com/shapeshift/web/blob/develop/src/context/AppProvider/AppContext.tsx#L231

**Comment by kaladinlight** [comment] 2024-08-08 20:02
There may have been a misunderstanding here whether the missing data was balance related or tx history related. Going to hold of on further debugging related to tx history until: https://github.com/shapeshift/web/pull/7522 is released which fixes balances on refresh and may be the issue at hand.

@shapeshift/operations after released, please keep an eye on support tickets related to cache clear issues due to us not updating correctly and based on that, we can close or continue debugging tx history accordingly. Also please confirm if the users falling into this issue are seeing their transaction or not to confirm tx history issues. Thanks!

**Comment by 0xean** [comment] 2024-08-19 22:06
closing for now since @shapeshift/operations believes the issue is resolved... can reopen or create new ticket if not

**Closed by 0xean** 2024-08-19 22:06 UTC
Labels: bug
