### ISSUE TITLE
Can sign portals trade and it doesn't show gas or protocol fee

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#8286] opened 2024-12-05 04:35 UTC
### Overview

For some protals trade noticing that you can sign a transaction before there is a fee for gas or protocol - trade doesnt complete but still shows to sign transaction

### References and additional details

![image](https://github.com/user-attachments/assets/ca351790-8b21-431e-b1cb-024a463b5fa0)
https://jam.dev/c/bb5c5dad-dd65-41c8-82dd-742d080c1377
https://jam.dev/c/88e12b59-6f2b-4644-bf5f-cc378885839e

### Acceptance Criteria

Should show gas and protocol fee before sign transaction

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment] 2024-12-05 04:55
This might actually be something spicy.

I just noticed something more sinister that could be related to this issue - data is persisting from the previous _quote_ to the current _rate_.

Recorded this jam for the easiest explanation: https://jam.dev/c/2d487e23-8fa7-4b95-a9b5-790061e06601

Summoning @gomesalexandre - is this expected behaviour from the rate implementation? It might well be, but it certainly _feels_ off.

**Comment by gomesalexandre** [comment] 2024-12-05 05:09
@0xApotheosis that's absolutely a bug and we should ensure we reset quotes (rates) i.e quote slice on swapper input mount, will get an issue spinned up for that 🙏🏽

**Comment by gomesalexandre** [comment] 2024-12-05 05:30
So the underlying issue here is actually Portals endpoint failing on slippage too low when getting the final quote:

<img width="889" alt="image" src="https://github.com/user-attachments/assets/5c2f2814-283d-4024-af0f-3cf53b18c5eb">

The bad news is we can't fix that straight away, since it's a chicken-and-egg scenario with our default slippage as it stands. The good news here are:
  - Autoslippage is in the plans for Portals and will eventually automagically work for us (assuming we consume it, which is a fewliner similar to Jupiter autoslippage work in https://github.com/shapeshift/web/pull/8253). We have an issue for it in https://github.com/shapeshift/web/issues/8193
  - the issue at hand here is not so much that the final quote failed, but that we're not surfacing the failure, making it look like the trade execution perma-spins, where in reality we have no final quote to execute. This is an error-handling issue, and will be fixed
  - the other way we can improve this is by using the same slippage as Portals default (2.5%). That won't solve things here in this specific swap (slippage at final quote time is ~3.8%), but could solve it for swaps currently failing where the final quote slippage is >1% (our current Portals default) and <=2.5% (Portals default)

**Closed** 2024-12-09 20:39 UTC
Labels: bug, needs engineering
