### ISSUE TITLE
Multicurrency Values Are In USD

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#2321] opened 2022-08-02 22:50 UTC
### Overview

When switching between different currencies, the values stay in USD. 

### References and additional details

1. go to app.shapeshift.com
2. log in with your preferred wallet 
3. change your default currency to something other than USD
4. notice the your values stay in USD

### Acceptance Criteria

the currency amount should change based on the currency you choose

### Screenshots/Mockups

<img width="815" alt="Screenshot 2022-08-02 184520" src="https://user-images.githubusercontent.com/99363597/182486641-7c863114-223b-41fe-b42a-b15b166c29c7.png">

**Comment by gomesalexandre** [comment] 2022-08-03 09:25
Not reproducible atm, was happening because of an outage of https://exchangerate.host

**Comment by 0xdef1cafe** [comment] 2022-08-12 19:45
closing as transient, should not occur again per fix in https://github.com/shapeshift/web/pull/2328

**Closed by 0xdef1cafe** 2022-08-12 19:45 UTC
Labels: needs engineering
