### ISSUE TITLE
Sym after RUNE asym deposit error message

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/web#6749] opened 2024-04-24 20:37 UTC
### Description

See https://discord.com/channels/554694662431178782/1232438076060733582/1232476818368630825

Spotted by @MBMaria - the "Sym deposits aren't possible after RUNE asym" pops up despite not having an asym RUNE position open for that asset

### Expected behaviour

The "Sym deposits aren't possible after RUNE asym" only shows if you have an actual asym RUNE deposit

**Comment by NeOMakinG** [comment] 2024-07-01 07:54
I did try to reproduce, couldn't at all, maybe the code evolved since then or it was a bug at that time

If someome goes there, try to reproduce and close the issue if you can't

**Closed** 2024-07-01 08:42 UTC
