### ISSUE TITLE
LiFi trade failure: POST Failed to execute 'clone' on 'Response': Response body is already usedhttps://li.quest/v1/advanced/stepTransaction

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#7278] opened 2024-07-01 14:57 UTC
### Overview

Currently in Production I am unable to perform my desired LiFI trade of a Max send of USDC on ARB to USDC on ETH. Continually blocked. 

### References and additional details

Here is a jam of the issue: 
https://jam.dev/c/c32a801c-ba3b-4106-9469-40db6ea007c6

### Acceptance Criteria

Users are able to perform LiFi trades without running into 'an error occurred'

**Comment by purelycrickets** [comment] 2024-07-01 14:58
attempted again incognito (didn't jam) and got this error for the same trade: 

Failed to load resource: the server responded with a status of 424 ()
2console.ts:36 TypeError: Failed to execute 'clone' on 'Response': Response body is already used
    at host-rrweb-network.js:2:76163
    at async ve (request.js:45:15)
    at async Object.getStepTransaction (ApiService.js:263:9)
    at async Object.getUnsignedEvmTransaction (endpoints.ts:87:13)
    at async tradeExecution.ts:130:15
    at async m._execWalletAgnostic (tradeExecution.ts:62:13)
    at async m.execEvmTransaction (tradeExecution.ts:144:5)
    at async useTradeExecution.tsx:222:17

**Comment by gomesalexandre** [comment] 2024-07-01 15:54
I wasn't able to repro on USDC.ARB -> USDC.Polygon, there may be something specific to USDC.ARB -> USDC.ETH Li.Fi route using across here

**Comment by kaladinlight** [comment] 2024-07-01 16:31
This is definitely on the LIFI side of things and out of our control. I will validate the payload being sent, but it looks like issues parsing their route responses that are being surfaced to us. This would be applicable to all `424`s from LIFI. I have seen things like "slippage too large" as well.

**Comment by kaladinlight** [comment] 2024-07-01 16:36
I was able to successfully trade USDC.ARB -> USDC.ETH Li.Fi via Symbiosis, so likely related to their internal handling of Across routes for the pair in question.

**Comment by NeOMakinG** [comment] 2024-07-01 17:38
Also tested Li.Fi.Accross

inbound: https://arbiscan.io/tx/0x69edb0e849a4be8acd076264555ca7c4712a411d2bd38d2c6c16d423eb00e5d1
outbound: https://etherscan.io/tx/0x87936964a7f7fa94e7767047c6ffb8a870ee401108e521620e203d529ba38046

I couldn't reproduce

**Comment by 0xean** [comment] 2024-07-01 22:30
closing as upstream issue, bumped sdk may help

**Closed by 0xean** 2024-07-01 22:30 UTC
Labels: bug, needs engineering
