### ISSUE TITLE
KeepKey Unable to Claim FOXy 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#2275] opened 2022-07-28 22:08 UTC
### Overview

When viewing the FOXy vault on KeepKey, you are unable to claim FOXy if you have an available balance.

### References and additional details

1. go to app.shapeshift.com
2. log in with keepkey
3. go to the DeFi tab
4. go to you FOXy vault 
5. Click on the Claim bottom if you have an available balance
6. Notice the Confirm Claim button is greyed out and you are unable to broadcast a FOXy claim

### Acceptance Criteria

You should be able to confirm and claim your FOXy, a tx should broadcast 

### Screenshots/Mockups

<img width="380" alt="Screenshot 2022-07-28 175415" src="https://user-images.githubusercontent.com/99363597/181645618-17f594bf-d99b-4ea4-b849-0a6e7ea480d6.png">

**Comment by brymut** [comment] 2022-09-22 05:04
Hi @wesleygravess, I cannot reproduce the error. Confirming and claiming FOXy & broadcasting tx works as expected.

https://user-images.githubusercontent.com/14836056/191662443-47da2d05-9b9f-4f54-8925-902af0eeaf81.mov

**Comment by MBMaria** [comment] 2022-09-22 20:32
@brymut  i tried just now but am unable to claim fox on kk currently. 
![image](https://user-images.githubusercontent.com/100157997/191845130-5a7e752a-5bcd-4494-920c-52bf1396ea19.png)

**Comment by wesleygravess** [comment] 2022-09-22 20:35
I don't have any withdraws to claim at the moment on kk

**Comment by gomesalexandre** [comment] 2022-09-22 20:47
@MBMaria @wesleygravess I also don't have FOXy to claim currently but had tested it as part of https://github.com/shapeshift/web/pull/2795 - will re-test it to ensure we can close this as soon as rebase happens and I have FOXy to claim.

**Comment by foufrix** [comment] 2022-09-30 08:28
Will confirm if it works or not in 9 days when claims are available on my side

**Comment by foufrix** [comment] 2022-10-25 12:50
my bad I was busy the past weeks. Taking a look at it tomorrow.

**Comment by foufrix** [comment] 2022-10-27 14:24
Hi, @MBMaria 
Unfortunately, I cannot reproduce the bug. Can you verify this on your side? Maybe it's related to when you locked your FOX.

Here is a video: https://www.loom.com/share/ff192689b49b422ab037c95a1e2a597b

I do not have enough ETH on my Keepkey account that's why it dropped. Otherwise, it seems that I can send the transaction.

**Comment by wesleygravess** [comment] 2022-10-28 19:18
I was able to complete a foxy claim on kk 

<img width="841" alt="image" src="https://user-images.githubusercontent.com/99363597/198715202-500a2fa0-b516-4d45-8a03-b7b37ef37965.png">

**Closed** 2023-04-14 00:48 UTC
Labels: needs engineering, keepkey, keepkey-bounty
