### ISSUE TITLE
Send of Atom modal doesnt update once the transaction has completed

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7777] opened 2024-09-20 06:14 UTC
### Overview

When doing a send of Atom the send modal stays on waiting for confirmation and doesn't change to Success once the transaction has completed

### References and additional details

![image](https://github.com/user-attachments/assets/d2554e02-22d2-4865-bdf4-bd749f49d6ad)

https://jam.dev/c/f8ffb575-0bc0-4895-af4b-10a923ac6bd3

### Acceptance Criteria

Modal should update once send has completed

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by kaladinlight** [comment] 2024-10-01 16:43
@MBMaria can you try and confirm this again on your end? Cosmos tx handing in unchained was completely broken at one point and thinking this was the cause, but not sure if this was seen after that fix.

I just tested on my end and saw the confirmation right away:
![image](https://github.com/user-attachments/assets/cb0c468d-b4da-46cd-ba06-0348de208df2)

**Comment by MBMaria** [comment] 2024-10-01 22:21
hi @kaladinlight  I'm still experiencing this. using a chrome incognito tab just now. 
![image](https://github.com/user-attachments/assets/ec4402c4-c15c-4edc-a1c3-12d7d6179c17)

**Comment by kaladinlight** [comment] 2024-10-07 22:03
I have seen it as well, seems like the websockets degrade the longer they are up. Tried to push a small change and some additional debug logs to try and track things down more.

**Comment by kaladinlight** [comment] 2024-10-08 16:01
Changes look to have made a difference. Seeing detected transaction all through yesterday afternoon and again this morning. Can you give another spot check on your end @MBMaria please :pray:

**Comment by kaladinlight** [comment] 2024-10-08 21:54
Damnit, just checked again and no update. So that means the websockets are just stopping sending data on the node side of things while technically staying alive so we don't trigger a reconnect. I have a couple more thoughts and will hopefully get to the the bottom of this soon.

**Comment by kaladinlight** [comment] 2024-10-29 16:36
Ok, most recent ws durability improvements look to be working. Going to close this at this time. If there are more issues or instances, would like to open up a fresh ticket to start looking into again.

**Closed by kaladinlight** 2024-10-29 16:36 UTC
Labels: bug, needs engineering
