### ISSUE TITLE
FOXy 7-14 Day Withdrawal/Claim Not Working 

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#2151] opened 2022-07-12 16:53 UTC
### Overview

unable to withdrawal/claim 7-14 day FOXy stake. getting transaction failed error 

### References and additional details

1. go to app.shapeshift
2. log in with a wallet that you can claim a FOXy 7-14 day withdrawal
3. go to the DeFi section to view your FOXy position
4. Attempt to claim you 7-14 day withdrawal
5. Notice that it fails and you get a "Transaction Failed" error

### Acceptance Criteria

You shouldn't get the transaction error when claiming your 7-14 day FOXy withdrawal. A TX should broadcast and you should have access to your funds 

### Screenshots/Mockups

<img width="944" alt="Screenshot 2022-07-12 123209" src="https://user-images.githubusercontent.com/99363597/178549177-d522dd41-1b7f-40b7-b54c-0a62200ba4ed.png">
<img width="598" alt="Screenshot 2022-07-12 123904" src="https://user-images.githubusercontent.com/99363597/178549182-b47ec799-78b0-45a2-a1c2-2a460e241b9d.png">

**Comment by gomesalexandre** [comment] 2022-07-12 17:00
Duplicate of https://github.com/shapeshift/web/issues/2103

**Comment by gomesalexandre** [comment] 2022-07-29 13:27
@wesleygravess Can we have a retest on this one? The front-end flow has been revamped in #2103 - there is still an underlying bug being investigated in https://github.com/shapeshift/lib/issues/921, but at least users shouldn't get in this wrong state anymore to start with.

**Comment by wesleygravess** [comment] 2022-08-11 15:57
sorry for the delay, yes the 7-14 day claim in now working

**Closed** 2023-02-05 23:47 UTC
