### ISSUE TITLE
Enable native wallet and keepkey users to view their portfolio without unlocking their wallet

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#3327] opened 2022-11-14 22:46 UTC
### Overview

We want users to be able to view their portfolios without having to unlock their wallet every time. 

They should be prompted only when executing transactions, such as adding an account or signing a transaction (send, trade, deposit, etc)

They should not need to unlock on refresh.

### References and additional details

see above

### Acceptance Criteria

As a user, I don't want to have to unlock my wallet every time I view my portfolio.

**Comment by DiggyDiggy2** [comment] 2023-02-24 18:42
@gomesalexandre spiked into this. Est days of work:2.

**Comment by 0xdef1cafe** [comment] 2023-05-02 22:59
closing as dupe of #1646

**Closed by 0xdef1cafe** 2023-05-02 22:59 UTC
Labels: enhancement, cleanup
