### ISSUE TITLE
Link to block explorer page from asset

### ISSUE THREAD

**Issue by mrnerdhair** [shapeshift/web#1188] opened 2022-03-16 20:56 UTC
### Overview

The asset details page should include an explorer link to the asset if one is available. (For example, https://app.shapeshift.com/assets/eip155:1/erc20:0xc770eefad204b5180df6a14ee197d99d808ee52d should have a link somewhere to https://etherscan.io/token/0xc770eefad204b5180df6a14ee197d99d808ee52d.)

### Reference

This will require discussion with product to figure out all the places this sort of link might be relevant, but I suspect it might go at least in `src/components/AssetAccountDetails.tsx`.

### Acceptance Criteria

- Asset details page (and anywhere else product deems appropriate) should contain a link somewhere to the `asset.explorer` URL.

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment] 2022-03-17 18:54
closing as duplicate of https://github.com/shapeshift/web/issues/1180

**Closed by 0xdef1cafe** 2022-03-17 18:54 UTC
Labels: needs bounty, needs product
