### ISSUE TITLE
Naming of completed LIFI trades in transaction history needs work

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4271] opened 2023-04-14 02:55 UTC
### Overview

Certain pairs of lifi trades have transactions that aren't name correctly.

### References and additional details

1) Complete lifi trade Avax to Eth on Optimism and note how it appears in recent transactions
2) Complete USDC on Optimisn to Avax lifi trade and note transactions

![image](https://user-images.githubusercontent.com/100157997/231929557-911fca1e-049f-4fda-aa5c-69e90044554e.png)
![image](https://user-images.githubusercontent.com/100157997/231929586-97e31c98-6ac5-4a46-a862-d305b487f52b.png)

### Acceptance Criteria

Trades should be correctly named in tx history

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment] 2023-04-14 07:16
USDC on optimism to USDT on avax
![image](https://user-images.githubusercontent.com/100157997/231971392-560a3bb5-7da4-483d-980e-323e954d989a.png)

**Comment by MBMaria** [comment] 2023-04-26 00:03
![image](https://user-images.githubusercontent.com/100157997/234433336-e9d16a7a-ec4d-48cc-8716-d73cab7378de.png)
ETH to ETH on Optimism on KK

**Comment by woodenfurniture** [comment] 2023-05-29 22:16
I've closed https://github.com/shapeshift/web/pull/4557 as it parses bridge transactions into `send` and `receive` which is actually incorrect. These items are actually transactions which is what production is saying, and while it's unclear to the user what these are its actually more correct than my initial PR was displaying.

We'll likely need a way to extract some of the user centric data out of these transactions and display them in the UI. Etherscan does this with `transaction action` to show a transaction as containing multiple swaps etc:
![image](https://github.com/shapeshift/web/assets/125113430/2506a58f-6073-408e-b3ab-a36eb1c02964)

**Comment by purelycrickets** [comment] 2023-08-29 21:26
I believe this is not in as bad of a state as when first reported. @MBMaria are we still having issues here?

**Comment by MBMaria** [comment] 2023-08-29 23:43
probably not as bad and not a huge issue, but still happening for some assets. these are trade for optimism and avax
![image](https://github.com/shapeshift/web/assets/100157997/aff85f02-890d-49af-8d98-c2a33d72c0f3)
![image](https://github.com/shapeshift/web/assets/100157997/be2ad32c-56d4-4003-a3af-2188197dcb83)

**Comment by woodenfurniture** [comment] 2023-11-20 22:26
Closing as is working as intended from unchained side (CC @kaladinlight )

**Closed by woodenfurniture** 2023-11-20 22:26 UTC
