### ISSUE TITLE
back arrow on the send modal asset list is a dead click

### ISSUE THREAD

**Issue by wesleygravess** [shapeshift/web#2735] opened 2022-09-13 22:20 UTC
### Overview

The back arrow on the cosmos send modal asset list is a dead click.

### References and additional details

1. go to app.shapeshift.com 
2. log in with native or kk
3. go to the cosmos asset page
4. click on the send button, input an address, and click next
5. click on the cosmos asset
6. notice an asset list pops up 
7. click the back arrow and notice it is a dead click

### Acceptance Criteria

the back arrow on the asset list should go back to the previous page of the send modal

### Screenshots/Mockups

https://user-images.githubusercontent.com/99363597/190019479-1d0ee975-f656-457f-8995-b00760c6f503.mp4

**Comment by 0xdef1cafe** [comment] 2022-10-04 19:36
without reviewing, this may be fixed by https://github.com/shapeshift/web/pull/2939

**Comment by gomesalexandre** [comment] 2022-10-05 14:39
> without reviewing, this may be fixed by #2939

Still happening with #2939, but will most likely be fixed with full consolidation, will stack another PR on top of it to fully consolidate the Cosmos form

**Comment by gomesalexandre** [comment] 2022-10-05 16:26
@wesleygravess Managed to reproduce this one for all sends, although selecting Cosmos initially seems to be what's breaking it - works when initially being on a send modal other than Cosmos

**Closed** 2022-10-10 04:06 UTC
Labels: multiple accounts, cleanup
