### ISSUE TITLE
Unable to connect dApps on mobile app

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5589] opened 2023-11-08 01:11 UTC
### Overview

Cannot connect to a dApp on the mobile app currently

### References and additional details

1) Open mobile app and connect to native wallet
2) Navigate to menu and select "Connect to dApp"
3) Enter an address or scan a qr code
4) Note that the Connect button is a dead click 

### Acceptance Criteria

Should be able to connect to a dApp on mobile app

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment] 2023-12-06 16:23
dApps section has been removed, closing

**Closed by 0xean** 2023-12-06 16:23 UTC
Labels: needs engineering

**Comment by MBMaria** [comment] 2023-12-06 23:40
Are we not going to have the option to connect to a dApp on mobile any more? 
Because currently you can and this is what is broken
 ![image](https://github.com/shapeshift/web/assets/100157997/83c8a484-4702-49c1-b3ec-d1f2a1e17f64)

**Comment by firebomb1** [comment] 2024-03-01 16:32
> dApps section has been removed, closing

@0xean  The section with the dApps listing has been removed, but the feature to connect a ShapeShift wallet to a dApp still exists. Can this be re-opened and fixed? It still is broken on mobile (Android I can confirm, and iOS seems to be confirmed by @MBMaria ).

**Comment by 0xean** [comment] 2024-03-01 19:31
See #6008 - definitely will fix. On Mar 1, 2024, at 12:32 PM, firebomb1 ***@***.***> wrote:﻿

dApps section has been removed, closing

@0xean  The section with the dApps listing has been removed, but the feature to connect a ShapeShift wallet to a dApp still exists. Can this be re-opened and fixed? It still is broken on mobile (Android I can confirm, and iOS seems to be confirmed by @MBMaria ).

**Comment by firebomb1** [comment] 2024-03-01 21:37
Oh awesome, my bad.
