### ISSUE TITLE
Difference in fee stated on ShapeShift vs MM pop up

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7807] opened 2024-09-25 06:33 UTC
### Overview

When looking at the fee ShapeShift quotes for a trade, it is less than what it stated on the MM pop up window. For one trade I completed just now, the fee ended up being about in the middle

### References and additional details

![image](https://github.com/user-attachments/assets/21be7f4e-e54f-4870-99e6-b067801ce672)

https://jam.dev/c/7d461c3f-df6c-4be5-bbc6-f60e00e244e0

### Acceptance Criteria

Fee should be the same or similar stated on ShapeShift and MM

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment] 2024-09-25 11:20
FYI this isn't only MM specific, noted the same with e.g Jumper and other DeFi dApps over the last days (e.g trades quoted at ~$10 gas in dApp but $30+ in MM. @kaladinlight may have some context WRT those discrepancies?

**Comment by gomesalexandre** [comment] 2024-11-29 03:04
Looks like this has been fixed by the quotes vs. rates fix @MBMaria as we now have the same fee, or close enough (at least nothing like half/twice the fee or more)

<img width="958" alt="image" src="https://github.com/user-attachments/assets/c86135ea-57d0-419a-bf78-f6a4b53633cc">
<img width="1313" alt="image" src="https://github.com/user-attachments/assets/3b2d242c-d765-4e9d-a7b4-bb2ec6de5066">


<img width="1309" alt="image" src="https://github.com/user-attachments/assets/92e03098-874f-4cdb-b834-40d431f1670f">

<img width="1217" alt="image" src="https://github.com/user-attachments/assets/2c061408-8e82-463b-a9bc-15bc006df38b">


Note, Li.Fi is still off but is on them upstream as they return network fees which are absolutely wrong and we leverage that:

<img width="1315" alt="image" src="https://github.com/user-attachments/assets/26f8477f-d650-48e0-999d-b909dfe438c6">
<img width="930" alt="image" src="https://github.com/user-attachments/assets/9368000b-6d86-467b-bd5f-678383f96b2c">

(Note, the small discrepancy between LiFi's `gasCostUSD` and our USD value is expected as we don't leverage it directly, but rather leverage the crypto gas cost estimates there so fiat rates can vary slightly)

Wondering if we can consider it solved by now, knowing that most are fixed, and Li.Fi just cannot?

**Comment by gomesalexandre** [comment] 2024-11-29 03:24
Confirmed with @MBMaria in DM we're good to close this guy!

**Closed by gomesalexandre** 2024-11-29 03:24 UTC
Labels: bug, needs engineering
