### ISSUE TITLE
Trade UI shimozzle while accounts are loading

### ISSUE THREAD

**Issue by woodenfurniture** [shapeshift/web#7740] opened 2024-09-11 22:02 UTC
### Overview

When the accounts are loading, the trade UI goes into a state where everything looks broken until the accounts are finished loading. 

Depending on the wallet, this can take anywhere between 5 seconds to 5 minutes, during such time the user is led to believe the app is possibly broken (since "Loading Accounts" is only 1 of several different messages)

### References and additional details

The button says "Loading Accounts", but the rest of the UI thinks everything is broken:
- "No rate available"
- "You get" is 0
- "No Ethereum address found from connected wallet"

![image](https://github.com/user-attachments/assets/3ffef45e-39c6-4d79-835f-01b1c04a88ce)- 

### Acceptance Criteria

.

**Comment by 0xApotheosis** [comment] 2024-09-11 22:09
Ah damn, this should have been fixed in https://github.com/shapeshift/web/issues/7419.

**Comment by NeOMakinG** [comment] 2024-09-12 10:06
> Ah damn, this should have been fixed in #7419.

Yes we need to consume `isAccountMetadataLoading` in a few more places, it's currently consumed only in the button but we should add it at some other places, I'll pick this up today

**Comment by NeOMakinG** [comment] 2024-09-12 14:42
Trying to find every edge cases in https://github.com/shapeshift/web/pull/7741 even thought I couldn't reproduce your particular case in this issue @woodenfurniture 

As it's swapper, it's a high risk issue, could you please be one of the reviewers to see if your case is now handled? I think it was due to the fact that the component was lazy loaded before the accounts metadata are loading but as I couldn't reproduce, it's hard to be 100% sure...

Anyway the handling looks great now from my pov, let me know if we could improve it somehow!

**Closed** 2024-09-12 23:25 UTC
Labels: bug
