### ISSUE TITLE
Asset selection from Accounts page not working when more than 2 Eth accounts

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#3207] opened 2022-11-01 21:52 UTC
### Overview

When trying to select an asset from the accounts page when there are more than 2 Eth accounts, the asset wont load if selecting it from account 1. It just reloads the main accounts page.

### References and additional details

1) Log into app.shapeshift and connect to a wallet that supports multi accounts
2) Navigate to the accounts page and add 2x Eth accounts
3) Drop down the assets from account 1 and notice when selecting the asset it just brings you back to the main account page. (Selecting Eth will take you to the asset page, but not the other assets)

https://user-images.githubusercontent.com/100157997/199348579-7e116590-b807-4b16-83c6-242d5902ba79.mp4

### Acceptance Criteria

Selecting asset should take you to the asset page, not to the account main page

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment] 2022-11-01 22:19
@MBMaria please bounty, 3 hours.

**Comment by crowicked** [comment] 2022-11-03 03:26
@0xApotheosis not sure if related, but looks like it might be: https://github.com/shapeshift/web/issues/3216

**Comment by 0xApotheosis** [comment] 2022-11-03 03:35
Yes, I suspect it is @crowicked! @stackedq#1454 is already assigned to the other one, so I'm inclined to un-bounty this.

**Comment by 0xApotheosis** [comment] 2022-11-03 03:54
@0xtekgrinder please ensure the issue in https://github.com/shapeshift/web/issues/3216 is met, too.
I think it's all the same root cause, but please crosscheck.

**Closed** 2022-11-04 18:18 UTC
Labels: bounty, cleanup
