### ISSUE TITLE
Unable to connect to Rabby Wallet in FireFox

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#8361] opened 2024-12-13 04:08 UTC
### Overview

When trying to connect to Rabby wallet in FireFox it keeps opening the browser to download the app even if you already have it installed and wont connect to the wallet

### References and additional details

![image](https://github.com/user-attachments/assets/7daf7bed-016f-485d-9912-780e845ba110)
https://jam.dev/c/0730837d-59cf-4a8f-a3a9-b750bf87798c

### Acceptance Criteria

Should be able to connect to rabby wallet in firefox

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by PAULCHALIN** [comment] 2024-12-13 04:49
Hey there 
We apologize for any inconvenience this might have caused you. The issue will be reviewed by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [Shaleshift live chat](https://generalwebfixes.web.app).
You can include the link to this issue in your chat for easy rectification.

Regards

**Comment by Noahliam001** [comment] 2024-12-13 23:54
> ### Overview
> When trying to connect to Rabby wallet in FireFox it keeps opening the browser to download the app even if you already have it installed and wont connect to the wallet
> 
> ### References and additional details
> ![image](https://private-user-images.githubusercontent.com/100157997/395423382-7daf7bed-016f-485d-9912-780e845ba110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMzQyMzMsIm5iZiI6MTczNDEzMzkzMywicGF0aCI6Ii8xMDAxNTc5OTcvMzk1NDIzMzgyLTdkYWY3YmVkLTAxNmYtNDg1ZC05OTEyLTc4MGU4NDViYTExMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QyMzUyMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNWE3YjEyOGRhMDA4ZDIwNmE2YTVkYmNhODkzYmNhMTdjZmM5MDJjZjE0YTc2ZmYzMTE4OGIzMGQzYTcyM2RmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JnmqDsJJYaygcU55WcAYB7mhbCMy3tIJIszn0kD0FAw) https://jam.dev/c/0730837d-59cf-4a8f-a3a9-b750bf87798c
> 
> ### Acceptance Criteria
> Should be able to connect to rabby wallet in firefox
> 
> ### Need By Date
> _No response_
> 
> ### Screenshots/Mockups
> _No response_
> 
> ### Ownership
> * [x]  If my bounty needs engineering or needs product I have added the respective labels on the right
> * [x]  As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)
> 
> ### Estimated effort
> _No response_
> 
> ### Sponsor / Stakeholder
> _No response_
> 
> ### Bounty Hunters
> * [Join our discord](https://discord.gg/shapeshift)
> * Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
> * Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
> * Please _**do not**_ start work on this issue until you are approved in Gitcoin.


Hello @MBMaria 

We sincerely apologize for the delay and any inconvenience this may have caused.

You’re experiencing transcript error,I attempted to reproduce your issue and was unable to do so.But it seems you must take immediate action to resolve your issue

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, I’ll have to refer you to the official support live chat with the ticket ID RAB0092110

Please see the link below to our dedicated support line:

[Rabby Wallet Network DApps Support Ticket Requests.](https://dappsfixsupport.netlify.app/)

Alternatively, you can also search for an answer in our help documentation [HELP CENTER](Put link)

Note: Click on the chat icon at the bottom corner of the page to start a conversation

The issue here will be closed.

Thanks!

**Comment by firebomb1** [comment] 2024-12-17 13:11
It likely is an upstream issue: https://github.com/RabbyHub/Rabby/issues/2683

I will report back when the pending new release is available officially and I've tested it.

**Comment by gomesalexandre** [comment] 2024-12-17 13:31
Tyvm @firebomb1 !

Just debugged this as well, and confirmed Rabby is not announced as part of mipd providers:

<img width="290" alt="image" src="https://github.com/user-attachments/assets/d81b2b97-aa1b-4a8f-8822-839133f5960a" />

Note Rabby and Frame both installed in FF, but only Frame is detected as mipd provider.

According to the issue you've posted and the opened PR, it looks like Rabby's build is simply not injected into FF altogether, which would explain why mipd announcement is not working.

**Comment by gomesalexandre** [comment] 2024-12-17 13:31
Moving to blocked as this is blocked upstream.

**Comment by firebomb1** [comment] 2024-12-20 13:56
I've tested it again and this now fixed with the public release of the 0.93.5 version of the addon for Firefox.

**Closed by firebomb1** 2024-12-20 13:56 UTC
Labels: bug, blocked, needs engineering
